#grid(
  columns: (1fr, 3fr),
  row-gutter: 1.5em,

  [Valdeabella:], [Good afternoon po! Ako po si Seanrei Ethan Valdeabella.],
  [Macapallag:], [Ako po si Mhar Andrei Macapallag.],
  [Javier], [Ako po si Geron Simon Javier.],
  [Valdeabella:],
  [We are computer science students from Laguna State Polytechic University sa Santa Cruz lang po. Unang una, thank you po sa time and opportunity para maisagawa itong interview. We are conducting research titled "Probabilistic Detection of Systemic Diseases using Deep Learning on Fingernail Biomarkers." Ang objective po ng study namin ay makagawa ng algorithm na makakapag infer ng systemic diseases base sa fingernails. Hindi po nito papalitan yung tunay na diagnosis---sa experts pa rin po yun. Ang goal lang po ng app na to is first aid lang po ganun.],
  [Javier], [Complementary tool po],
  [Macapallag], [Tool or assistance po siya.],
  [Valdeabella:], [For example, may mga taong malayo sa ospital. Halimbawang may ganto silang nail disease, gagamitin nalang nila yung app para makita kung may sakit yung ano nila. Simula doon, madedetermine kung anong nail disease yung meron sila tapos base sa nail disease na yun, maiinfer kung ano yung kaakibat na systemic disease nila. If it's something serious, irerecommend po nung app na magconsult sa experts---sa inyo po. Kaya dapat po, talagang accurate and reliable yung magiging system namin. We appreciate your expertise and insights as a dermatologist. May mga tanong lamang po kami para mas maintindihan yung clinical and diagnostic relevance ng nail diseases sa mga systemic diseases. Before we start, can you please tell us about yourself including name, educational background, and professional background kung okay lang po.],
  [Expert:], [I'm Cristine Florentino. I graduated from University of Santo Thomas under Doctor of Medicine and I had my three-year residency _[inaudible]_ at Ospital ng Maynila Medical Center.],
  [Valdeabella:], [Sa una po ay sa general experience po. Nakakita na po ba kayo ng mga cases na yung nail disease ay may kinalaman sa sakit or systemic diseases?],
  [Expert:], [Yes],
  [Valdeabella:], [Sa tingin niyo po, gaano ka-reliable yung mga nail diseases or disorders or---ano po ba yung tamang term po dun? Nail disease or disorders?],
  [Expert:], [Generally yes, but it depends because merong mga nail features that are not exclusive to one disease. For example, let's take psoriasis. It's a systemic condition eh. Pero, it has nail features that you can probably share with alopecia---yung naglalagas yung buhok or yung mga bald spots. For example, like when you see nail pits---meaning yung mga baon-baon sa nails. So you can see it in psoriasis pero hindi siya exclusive to that condition. You also see that in other skin conditions din. Pero meron din naman siyang what we call 'pathognomonic sign' or detailed nail sign meaning---pag ito nakita mo to, most likely ito yung condition niya. So when you see a different feature---for example---in psoriasis we see oil spots _[shows book to demonstrate the appearance of psoriasis]_. When you see that, most likely psoriasis siya. May mga features na ganun so it depends like---may mga iba na it would just narrow down your diagnosis na ano bang meron nitong pasyente na to. Syempre yung nail is just one thing that you look at. Yung iba sa checklist mo _[inaudible]_],
  [Valdeabella:], [So, sa tingin niyo po, gaano ka-reliable yung systemic diseases _[sic]_ [nail features] para---ay---ano],
  [Expert:], [It will be able to narrow down---I guess---yung differential. Parang...],
  [Valdeabella:], [Parang part po siya pero hindi po siya yung whole?],
  [Expert:], [Male-lessen yung iniisip mo. Okay ito yung feature na to, so ano nalang yung pagpipilian mo? Saan ba siya present?],
  [Valdeabella:], [Next question. May mga specific po bang nail diseases or disorders na lagi niyong tinitingnan kapag nagpapacheck-up po yung mga pasyente?],
  [Expert:], [Common cases yun ba yung tanong mo?],
  [Valdeabella:], [Kung meron po kayong specific nail disorders na parang binabantayan ganun.],
  [Expert:], [Well kasi sometimes it's either yun nalang yung chief complaint nung patient. Minsan, talagang may patients na darating---ang concerns nila ay yung nails nila. Kumbaga 'Ah ganito, ganito yung nakikita ko sa nails ko' so yun talaga yung concerns nila or baliktad naman kaya ng sinasabi mo---meron akong consideration and then I double check the nails kung meron siyang features na hinahanap ko. For example, fungal infection. Widespread. Syempre ang concern niya---una---yung katawan, pero titingnan ko din yung nails kase widespread na yung kaniyang condition. Meron na din kailangan i-treat kumbaga. So it works both ways. Pedeng yung nails talaga yung concern nila or systemically yung concern nila pero ichecheck mo rin yung nails kasi it ties up para ma-clinched yung diagnosis.],
  [Valdeabella:], [Next po ay sa diagnosis and clinical relevance po ng mga nail. In your practice, how often do you encounter nail disorders or diseases that are associated with systemic diseases.],
  [Expert:], [How often?],
  [Valdeabella:], [Opo, parang gaano kadalas po mayroong kaakibat na sakit yung mga nail abnormalities po?],
  [Expert:], [Siguro in about 20%. But the most common na systemic talaga is psoriasis. Meron talagang nail changes dun. Minsan doon ko nakikita if matagal na ba yung problem niya. Kase minsan pag ininterview mo 'eto ano lang to eh, last month lang' ganun. So pu-pwedeng doon mo makikitang 'hindi parang matagal ka nang may condition talaga, siguro di lang napapansin' pero it's mostly that. When it comes to systemic conditions and nail findings, the most common---I think---would be psoriasis.],
  [Valdeabella:], [Ano-anong systemic diseases po usually ang may nail biomarkers sa clinic niyo?],
  [Expert:], [Psoriasis, sometimes alopecia meron, tinia pwede rin. Yun, more commonly.],
  [Valdeabella:], [Next question. Are there nail disorders that you consider strong or near definitive indicators of systemic conditions? Yung parang sure sign na na ganto yung sakit kapag ganto yung kuko ganun.],
  [Expert:], [Oil spots in psoriasis, green nails for pseudomonas---pseudomonas green nails. The rest are parang overlapping eh with other possible diagnosis.],
  [Javier:], [Edi yung iba po ay parang katulong nalang nung ano...],
  [Expert:], [Parang kailangan mo pang mag investigate further for other signs to clinch definitive diagnosis. Melanoma pwede rin. Very distinct naman yung features niya.],
  [Valdeabella:], [Yun po yung may lines sa kuko noh? Yung melanoma po.],
  [Expert:], [Hindi, yung sinasabi mo ay yung band lang na itim or brown eh. Yuun---I also see that---not as common though pero yun ang isa sa mga---let's say---people come in to consult 'ito ba ay nakakatakot o hindi?' but it's not always the case kase it's pretty common in brown skin meaning tayo---asians ganyan. Pwedeng it's something na 'okay lang wala naman siyang dapat ikabahala' pero pag may mga ibang---let's say---long-standing, you can suggest na biopsy for that. Minsan kase pwedeng nevus lang yun eh---parang nunal lang eh that is in your nail bed kaya nagkukulay yung nail plate mo. Ang melanoma ay mas panget yung itsura niya. Mas irregular yung borders...yun. What you're saying kase is this one eh _[showing the book]_.],
  [Valdeabella:], [Opo, ayan po yun.],
  [Expert:], [Nevus lang yan eh. Nunal lang yan eh. Nunal _[inaudible]_. Pag melanoma mas panget siya. Mas irregular yung border mo, iba-iba yung kulay, ganun, pero pareho silang black. But you see the difference---itim siya---pero syempre yung unang cause for concern ni pasyente 'Bakit siya itim?' diba. Pero if you look side-by-side, mas pangit yung itsura nito. This one is melanoma, this one is nevus.],
  [Valdeabella:], [Parang dito po sa isa, yung kulay lang po ang nagbago?],
  [Expert:], [Yun yung basic concern kase diba. Parang pupunta ka 'Ay ano ba tong itim na to? papacheck-up ko nga to.' but yung mga distinct features na _[inaudible]_ ganyan. Pero when you're in doubt, we do a biopsy just for peace of mind na din. Pero it---you know off the back---mas mataas yung chances na _[inaudible]_ sila.],
  [Valdeabella:], [Sa ibang examples po kaya like clubbing, pitting...],
  [Expert:], [Ano yung isa? Pitting?],
  [Valdeabella:], [Opo.],
  [Expert:], [Okay, ang clubbing kase is hypertension ba? Sa cardio yun usually eh diba? yung clubbing. Ang pitting mo is something like this _[Showing the book]_. Kita mo?],
  [Valdeabella:], [Yung may butas butas po.],
  [Expert:], [These are your oil spots. Eto yung sinasabi ko sayong greeny nail. Yung pitting kase is... _[inaudible]_ alopecia yan eh. Pwede rin pala ang mga drug-induced _[inaudible]_ yung mga black mark. So ganun din, hindi ka ba nagte-take ng mga oral medications kase yang mga naka chemo, nagkakaroon din ng mga black mark. _[inaudible]_ ito yung sinasabi mo ih, yung clubbing.],
  [Valdeabella:], [Opo.],
  [Expert:], [Di pala cardio ang clubbing. _[inaudible]_ cardiovascular. So it's very diverse. iru-rule out mo siya. _[inaudible]_. Pero ang nail pits mo, pwede kase siya in maraming conditions eh. Alam ko may alopecia din, minsan may atopic dermatitis din ang nail pits.],
  [Javier:], [Di ba po nasabi niyo kanina yung melanoma po ba? na mas common sa brown skin tama po ba?],
  [Expert:], [Ah hindi, yung melanonychia. Yung longitudinal melanonychia, eto. Yung parang hyperpigmented band sa nail crease.],
  [Javier:], [Sa mga asian tama po?],
  [Expert:], [Oo.],
  [Javier:], [Edi paano po kaya kung ibang ethnicity? Majority po ba ng mga nail disease is naiiba yung diagnosis base sa ethnicity po?],
  [Expert:], [Kunwari caucasian yan, magru-rule out ka ng melanoma. Kase di ba mas mataas ang _[inaudible]_ incidences sa kanila pero usually in brown skin, it's _[inaudible]_ pretty common na ganito, na pwedeng wala lang. Hindi siya necessarily _[inaudible]_.],
  [Javier:], [How about other nail diseases po?],
  [Expert:], [What do you mean other nail diseases?],
  [Javier:], [Halimbawa po yung clubbing...],
  [Expert:], [Ah kung anong ethnicity yun? ],
  [Javier:], [Okay lang po kahit ano?],
  [Expert:], [Oo. Parang wala namang ano yun.],
  [Valdeabella:], [Proceed na tayo sa next question? How do you differentiate between nail changes cause by external trauma versus those resulting from internal pathologies?],
  [Expert:], [Clinically, it's really hard just to look at photosor you just---off the bat---titingnan mo, but that's where your history will come in. You have to extract information also from patient. Yun yung one of the things na],
)
//20:45
