#grid(
  columns: (1fr, 3fr),
  row-gutter: 1.5em,

  [Valdeabella:], [Good afternoon po! Ako po si Seanrei Ethan Valdeabella.],
  [Macapallag:], [Ako po si Mhar Andrei Macapallag.],
  [Javier], [Ako po si Geron Simon Javier.],
  [Valdeabella:],
  [We are computer science students from Laguna State Polytechic University sa Santa Cruz lang po. Unang una, thank you po sa time and opportunity para maisagawa itong interview. We are conducting research titled "Probabilistic Detection of Systemic Diseases using Deep Learning on Fingernail Biomarkers." Ang objective po ng study namin ay makagawa ng algorithm na makakapag infer ng systemic diseases base sa fingernails. Hindi po nito papalitan yung tunay na diagnosis---sa experts pa rin po yun. Ang goal lang po ng app na to is first aid lang po ganun.],
  [Javier], [Complementary tool po],
  [Macapallag], [Tool or assistance po siya.],
  [Valdeabella:], [For example, may mga taong malayo sa ospital. Halimbawang may ganto silang nail disease, gagamitin nalang nila yung app para makita kung may sakit yung ano nila. Simula doon, madedetermine kung anong nail disease yung meron sila tapos base sa nail disease na yun, maiinfer kung ano yung kaakibat na systemic disease nila. If it's something serious, irerecommend po nung app na magconsult sa experts---sa inyo po. Kaya dapat po, talagang accurate and reliable yung magiging system namin. We appreciate your expertise and insights as a dermatologist. May mga tanong lamang po kami para mas maintindihan yung clinical and diagnostic relevance ng nail diseases sa mga systemic diseases. Before we start, can you please tell us about yourself including name, educational background, and professional background kung okay lang po.],
  [Expert:], [I'm Cristine Florentino. I graduated from University of Santo Thomas under Doctor of Medicine and I had my three-year residency _[inaudible]_ at Ospital ng Maynila Medical Center.],
  [Valdeabella:], [Sa una po ay sa general experience po. Nakakita na po ba kayo ng mga cases na yung nail disease ay may kinalaman sa sakit or systemic diseases?],
  [Expert:], [Yes],
  [Valdeabella:], [Sa tingin niyo po, gaano ka-reliable yung mga nail diseases or disorders or---ano po ba yung tamang term po dun? Nail disease or disorders?],
  [Expert:], [Generally yes, but it depends because merong mga nail features that are not exclusive to one disease. For example, let's take psoriasis. It's a systemic condition eh. Pero, it has nail features that you can probably share with alopecia---yung naglalagas yung buhok or yung mga bald spots. For example, like when you see nail pits---meaning yung mga baon-baon sa nails. So you can see it in psoriasis pero hindi siya exclusive to that condition. You also see that in other skin conditions din. Pero meron din naman siyang what we call 'pathognomonic sign' or detailed nail sign meaning---pag ito nakita mo to, most likely ito yung condition niya. So when you see a different feature---for example---in psoriasis we see oil spots _[shows book to demonstrate the appearance of psoriasis]_. When you see that, most likely psoriasis siya. May mga features na ganun so it depends like---may mga iba na it would just narrow down your diagnosis na ano bang meron nitong pasyente na to. Syempre yung nail is just one thing that you look at. Yung iba sa checklist mo _[inaudible]_],
  [Valdeabella:], [So, sa tingin niyo po, gaano ka-reliable yung systemic diseases _[sic]_ [nail features] para---ay---ano],
  [Expert:], [It will be able to narrow down---I guess---yung differential. Parang...],
  [Valdeabella:], [Parang part po siya pero hindi po siya yung whole?],
  [Expert:], [Male-lessen yung iniisip mo. Okay ito yung feature na to, so ano nalang yung pagpipilian mo? Saan ba siya present?],
  [Valdeabella:], [Next question. May mga specific po bang nail diseases or disorders na lagi niyong tinitingnan kapag nagpapacheck-up po yung mga pasyente?],
  [Expert:], [Common cases yun ba yung tanong mo?],
  [Valdeabella:], [Kung meron po kayong specific nail disorders na parang binabantayan ganun.],
  [Expert:], [Well kasi sometimes it's either yun nalang yung chief complaint nung patient. Minsan, talagang may patients na darating---ang concerns nila ay yung nails nila. Kumbaga 'Ah ganito, ganito yung nakikita ko sa nails ko' so yun talaga yung concerns nila or baliktad naman kaya ng sinasabi mo---meron akong consideration and then I double check the nails kung meron siyang features na hinahanap ko. For example, fungal infection. Widespread. Syempre ang concern niya---una---yung katawan, pero titingnan ko din yung nails kase widespread na yung kaniyang condition. Meron na din kailangan i-treat kumbaga. So it works both ways. Pedeng yung nails talaga yung concern nila or systemically yung concern nila pero ichecheck mo rin yung nails kasi it ties up para ma-clinched yung diagnosis.],
  [Valdeabella:], [Next po ay sa diagnosis and clinical relevance po ng mga nail. In your practice, how often do you encounter nail disorders or diseases that are associated with systemic diseases.],
  [Expert:], [How often?],
  [Valdeabella:], [Opo, parang gaano kadalas po mayroong kaakibat na sakit yung mga nail abnormalities po?],
  [Expert:], [Siguro in about 20%. But the most common na systemic talaga is psoriasis. Meron talagang nail changes dun. Minsan doon ko nakikita if matagal na ba yung problem niya. Kase minsan pag ininterview mo 'eto ano lang to eh, last month lang' ganun. So pu-pwedeng doon mo makikitang 'hindi parang matagal ka nang may condition talaga, siguro di lang napapansin' pero it's mostly that. When it comes to systemic conditions and nail findings, the most common---I think---would be psoriasis.],
  [Valdeabella:], [Ano-anong systemic diseases po usually ang may nail biomarkers sa clinic niyo?],
  [Expert:], [Psoriasis, sometimes alopecia meron, tinia pwede rin. Yun, more commonly.],
  [Valdeabella:], [Next question. Are there nail disorders that you consider strong or near definitive indicators of systemic conditions? Yung parang sure sign na na ganto yung sakit kapag ganto yung kuko ganun.],
  [Expert:], [Oil spots in psoriasis, green nails for pseudomonas---pseudomonas green nails. The rest are parang overlapping eh with other possible diagnosis.],
  [Javier:], [Edi yung iba po ay parang katulong nalang nung ano...],
  [Expert:], [Parang kailangan mo pang mag investigate further for other signs to clinch definitive diagnosis. Melanoma pwede rin. Very distinct naman yung features niya.],
  [Valdeabella:], [Yun po yung may lines sa kuko noh? Yung melanoma po.],
  [Expert:], [Hindi, yung sinasabi mo ay yung band lang na itim or brown eh. Yuun---I also see that---not as common though pero yun ang isa sa mga---let's say---people come in to consult 'ito ba ay nakakatakot o hindi?' but it's not always the case kase it's pretty common in brown skin meaning tayo---asians ganyan. Pwedeng it's something na 'okay lang wala naman siyang dapat ikabahala' pero pag may mga ibang---let's say---long-standing, you can suggest na biopsy for that. Minsan kase pwedeng nevus lang yun eh---parang nunal lang eh that is in your nail bed kaya nagkukulay yung nail plate mo. Ang melanoma ay mas panget yung itsura niya. Mas irregular yung borders...yun. What you're saying kase is this one eh _[showing the book]_.],
  [Valdeabella:], [Opo, ayan po yun.],
  [Expert:], [Nevus lang yan eh. Nunal lang yan eh. Nunal _[inaudible]_. Pag melanoma mas panget siya. Mas irregular yung border mo, iba-iba yung kulay, ganun, pero pareho silang black. But you see the difference---itim siya---pero syempre yung unang cause for concern ni pasyente 'Bakit siya itim?' diba. Pero if you look side-by-side, mas pangit yung itsura nito. This one is melanoma, this one is nevus.],
  [Valdeabella:], [Parang dito po sa isa, yung kulay lang po ang nagbago?],
  [Expert:], [Yun yung basic concern kase diba. Parang pupunta ka 'Ay ano ba tong itim na to? papacheck-up ko nga to.' but yung mga distinct features na _[inaudible]_ ganyan. Pero when you're in doubt, we do a biopsy just for peace of mind na din. Pero it---you know off the back---mas mataas yung chances na _[inaudible]_ sila.],
  [Valdeabella:], [Sa ibang examples po kaya like clubbing, pitting...],
  [Expert:], [Ano yung isa? Pitting?],
  [Valdeabella:], [Opo.],
  [Expert:], [Okay, ang clubbing kase is hypertension ba? Sa cardio yun usually eh diba? yung clubbing. Ang pitting mo is something like this _[Showing the book]_. Kita mo?],
  [Valdeabella:], [Yung may butas butas po.],
  [Expert:], [These are your oil spots. Eto yung sinasabi ko sayong greeny nail. Yung pitting kase is... _[inaudible]_ alopecia yan eh. Pwede rin pala ang mga drug-induced _[inaudible]_ yung mga black mark. So ganun din, hindi ka ba nagte-take ng mga oral medications kase yang mga naka chemo, nagkakaroon din ng mga black mark. _[inaudible]_ ito yung sinasabi mo ih, yung clubbing.],
  [Valdeabella:], [Opo.],
  [Expert:], [Di pala cardio ang clubbing. _[inaudible]_ cardiovascular. So it's very diverse. iru-rule out mo siya. _[inaudible]_. Pero ang nail pits mo, pwede kase siya in maraming conditions eh. Alam ko may alopecia din, minsan may atopic dermatitis din ang nail pits.],
  [Javier:], [Di ba po nasabi niyo kanina yung melanoma po ba? na mas common sa brown skin tama po ba?],
  [Expert:], [Ah hindi, yung melanonychia. Yung longitudinal melanonychia, eto. Yung parang hyperpigmented band sa nail crease.],
  [Javier:], [Sa mga asian tama po?],
  [Expert:], [Oo.],
  [Javier:], [Edi paano po kaya kung ibang ethnicity? Majority po ba ng mga nail disease is naiiba yung diagnosis base sa ethnicity po?],
  [Expert:], [Kunwari caucasian yan, magru-rule out ka ng melanoma. Kase di ba mas mataas ang _[inaudible]_ incidences sa kanila pero usually in brown skin, it's _[inaudible]_ pretty common na ganito, na pwedeng wala lang. Hindi siya necessarily _[inaudible]_.],
  [Javier:], [How about other nail diseases po?],
  [Expert:], [What do you mean other nail diseases?],
  [Javier:], [Halimbawa po yung clubbing...],
  [Expert:], [Ah kung anong ethnicity yun? ],
  [Javier:], [Okay lang po kahit ano?],
  [Expert:], [Oo. Parang wala namang ano yun.],
  [Valdeabella:], [Proceed na tayo sa next question? How do you differentiate between nail changes cause by external trauma versus those resulting from internal pathologies?],
  [Expert:], [Clinically, it's really hard just to look at photosor you just---off the bat---titingnan mo, but that's where your history will come in. You have to extract information also from patient. Yun yung one of the things na 'oh picture lang', hindi. Even with these, there's a thing [called] differential diagnosis. Kumbaga eto, it's a deformed nail. You have a list in your head kung ano ba yung pede na can look like this. Then from your history, dun mo siya mae-eliminate one-by-one. Kaya yung trauma---parang eto _[points at a picture in the book]_, it can look like trauma. Pwedeng naipit diba? Pwedeng trauma pa rin. But, yun yung mga iaano mo---it will probably require you to ask a little bit more para lang mas maging definitive siya lalo na when it comes to trauma. Minsan yun ang unang una magru-rule out eh. 'Hindi ba to naipit? Hindi ba to nabagsakan ng kung ano?' bago mo sabihing 'hindi, ano lang talaga, ganyan na talaga siya. Biglaan nalang siya nag iba ng itsura.'],
  [Valdeabella:], [In your opinion, is the interpretation of nail signs generally consistent among doctors or dermatologists, or physicians or nagvavary po siya depende talaga sa natingin?],
  [Expert:], [Well, when it comes to---I think there would be a difference if you would say a general physician and a specialist ang titingin. I mean yung assessment ko might be different from assessment of just a general practitioner kumbaga. Kase, skin changes, nail changes, are sub-specialties very visual. So talagang ang traning is a lot of comparisons. Sometimes yung nakikita ko is di nakikita ng ordinary na general practitioner kase iba yung additional training noon. It takes practice, kaya ang derm is a three-year sub-specialty practice pa kase talagang hindi mo siya makukuha ng isahang tingin mo lang sa picture. We have to compare it with other possible diagnoses for you to be able to clinch talaga or para ma-narrow down mo talaga kung ano nalang yung pagpipilian mo. And then, syempre dun na papasok yung diagnostics mo. Papano ba naten siya talaga maze-zero in kung ano yung condition niya. Dun ka na magpapatest, ganyan. But, if---for example---if within dermatologists, I think mas mataas yung chances mo of getting like a similar consensus kumbaga. It would vary on the training that your doctor has. I think it would vary a lot. Mas specialized yung training. Ano ba yung hahanapin mo? Ano ba yung iru-rule out mo? In comparison na pareho silang doctor pero yung isa is hindi naman siya talagang nag specialize ba.],
  [Macapallag:], [So based po sa experience po yun?],
  [Expert:], [Oo, tsaka I think your training would be the---kase hindi lahat ng tumitingin sa balat has undergo---the standard kase is a three-year training talaga. It's not a certificate workshop. It would vary between physicians depende na din sa training.],
  [Javier:], [So kung may nail disease po...],
  [Expert:], [I would suggest syempre you go to specialist talaga. Kase _[inaudible]_ ru-rule out.],
  [Valdeabella:], [Dito naman po sa next group ng mga tanong. Ang theme niya naman po ay 'Awareness and Epidemiological Context.'],
  [Expert:], [Okay.],
  [Valdeabella:], [Are there any nail signs that you believe are underrecognized or often overlooked by medical practitioners or patients?],
  [Expert:], [Medical practitioners? Parang wala naman. I mean overlooked? Parang it's the other way around eh. They notice more and then they just have to have it checked if it is something na---kailangan ba talaga nitong gamutin or pababayaan ko lang ba to? And this is _[inaudible]_. I think it's the other way around. Pag may napansin sila, 'ipa-check mo nalang kaya? Ipatingin mo nalang para sure.' We get refferals from other specialists or general practitioners to verify if it is something that they should investigate further or pababayaan naten siya. I think it's more on the other one rather than yung 'ay di niya nakita yung nails mo?'],
  [Valdeabella:], [Papalinaw lang po pala namin kung ano pong ibig sabihin niyo sa mga specialists?],
  [Expert:], [Kunwari we get refferals from IM. Kunwari they see 'oh may nail findings ka, pa-check mo na rin kaya yan?' So that's why---it's not that they overlooked. We often get referrals or sa amin pa pinapadala pag napansin nila just to check kung kailangan ba talagang---is it something concerning or wala lang ba yan?],
  [Valdeabella:], [Are there particular demographics like age group, gender, or pre-existing conditions in which systemic nail signs are more prevalent?],
  [Expert:], [Parang wala naman on a general note. It's very diverse. Yung mga systemic conditions and nail findings, parang wala. Elderly, adolescence ganun, children, it's the same.],
  [Valdeabella:], [Next question. What major patient factors or age, sex, or comorbidities should be considered when analyzing nail changes as possible biomarkers for systemic disease?],
  [Expert:], [Demographics ng patient tama ba?],
  [Valdeabella:], [Opo. Kung ano po ba yung pedeng maging factors kung baket po nagkaganun yung nails. Kung nakakaapekto po ba ang age ganun.],
  [Expert:], [Kung nakaka-affect ang age, gender, sa nail... ulet.],
  [Valdeabella:], [May mga major factors po ba kailangan namin i-consider like age or sex ganun?],
  [Expert:], [When it comes to nails? Parang wala naman. I think it's more of siguro what they do. Occupation ganun, rather than gender and age group. Kase your hands are used for manual ano din so it's more of _[inaudible]_.],
  [Valdeabella:], [Parang history lang po ng patient?],
  [Expert:], [Or like occupation. Is your patient a chemists? Kase you would think na kapag may exposure ka in your line of work sa mga irritants, baka yun pa yung pwedeng maging cause for your nail conditions rather than just saying na elderly and---kunwari---age and gender as _[inaudible]_. Baka yung occupation pa yung mas may cocontribute kumbaga.],
  [Javier:], [Bukod po sa occupation, meron pa po bang ibang makakapagcontribute kung bakit naging ganun yung nail? Yung pwede po naming kunin sa patient para malinawan?],
  [Expert:], [Your occupation, your---I would say hobbies pwede rin. Iisipin mo lang, ano ba yung madalas mong---kase you're talking about nails eh diba? So syempre what we gets in contact with _[inaudible]_ kase yun ang iru-rule out mo eh. Is it systemic or is it something na ano lang, nag change dahil sa ginagawa niya or what gets in contact with your nails. So yuun, occupation, your hobbies, where you use your hands for na pwedeng magkaroon ng---yeah. There are for example fungal nail, wala naman occupation na sa bahay lang. Mga laundry women mga ganun. Whatever it is that we can think of na involved si---the use of the nails. Iru-rule out mo.],
  [Valdeabella:], [So parang mas malaking factors po talaga kung anong ginagawa nila, hindi yung kung ano sila],
  [Expert:], [Oo, I think. Kase ang ano sayo is just the picture eh diba?],
  [Valdeabella:], [Opo.],
  [Expert:], [When it comes to demographics, baka mas makatulong pa yun rather than just male or female kase parang the occurence is more or less the same. And also kung elderly or bata, it would be the same.],
  [Valdeabella:], [Last section po para sa interview. Tungkol naman po to sa 'Expert recommendations.' Base po sa clinical expertise niyo, are there any specific nail diseases or disorders that you would recommend that we focused on this study?],
  [Expert:], [What systemic conditions inially that you have in mind?],
  [Valdeabella:], [Bale meron po kaming nakuha na pong public dataset ng mga nail diseases. Pwede po ba namin ipakita?],
  [Expert:], [Yeah. Para makita ko rin kung where the interest is coming from. ],
  [Valdeabella:], [Bale sampung classes---sampung nail diseases po.],
  [Expert:], [Okay. Para mas ma-narrow down din naten yung...],
  [Valdeabella:], [Nine po siya actually, excluding yung healthy nail.],
  [Expert:], [Ahh okay.],
  [Valdeabella:], [_[Showing the dataset.]_ Eto po yung mga nail diseases. Bale sa public dataset lang po namin siya nakuha.],
  [Expert:], [Ahh okay. Mga spoon nails mo. Ahh so it's a very ano lang...Hindi pero wala kang subset pa ng diseases? Like _[inaudible]_ disease yung mga ganun.],
  [Valdeabella:], [Wala po.],
  [Expert:], [Kase ito, these are nail features na. This is not a diagnosis. These are your...kase ito _[showing the book]_, when you say---kunwari ha---this is koilonychia. Koilonychia is basically spoon nail diba? When you look at koilonychia---edi papasa din to. This one is secondary to trauma. It's a habit before. Parang kinukutkot niya. So it's not...koilonychia per se is not---parang hindi siya systemic condition. Kase I was thinking---pag sinabing mong systemic, yung mga melanoma kase it's a cancer. Lupus. Yun yung akala kong systemic conditions na pasok si _[inaudible]_. Nail findings. But these are---eto ha---itong subset na to, it's more of physiscal examination findings ganun. Eto, _[inaudible]_ siya pero it will fall under your koilonychia...],
  [Javier:], [Bale pag halimbawa pong yan yung nadetect nung AI, ang sasabihin po namin is hindi siya systemic diseases?],
  //NOTE: acral lentiginous melanoma -> diagnosis
  [Expert:], [These are your physical examination findings so pwede yun. For example, yan ang idedetect niya. Is it clubbing? Is it beau's line? Is it melanoma? Is it nail pits? And then, what you can do is what are your conditions under these features? Like on beau's lines, it's usually from chemotherapy ganun. For koilonychia, ano ba yung mga diseases na pwede nateng i-associate with these physical examination findings? Your pitting, ano ba yung mga conditions na pwede? Parang _[inaudible]_ the differentials based on these physical examinations. Although ito, this is a diagnosis, acral lentiginous melanoma. Eto, diagnosis talaga. Hindi siya physical examination finding. Ang physical examination finding mo na jan is yung hyperpigmented nail plate pwedeng ganun.],
  [Javier:], [Sakit na po talaga yung acral lentiginous melanoma?],
  [Expert:], [Oo. Kase I was thinking kase like---for example---systemic di ba? Kunwari lupus. Lupus is a systemic disease pero meron siyang nail findings. Ang nail findings mo usually it has red dots in your nail fold ganun. Pero ang condition mo na systemic na ico-consider mo is lupus parang ganun. So eto, di ba---it's hyperpigmented nail tip mukha siyang melanoma pero trauma can still be a differential.],
  [Javier:], [Bale ang gagawin po namin, halimbawa po nadetect is yung ganyan...],
  [Expert:], [Oo, magdetect ka siguro ng physical examination finding ng nail and then from there, ano ba yung mga possible diseases that have these physical examination nail findings.],
  [Javier:], [So sa ganun po, may mga probabilities po yun?],
  [Expert:], [Oo, para lang mas maano yung flow mo. Kase yun yung gusto niyo di ba? From a photo, ide-detect ng AI yun para makapag suggest siya kung anong next step na gagawin. So yun, it's more of physical nail findings tapos ano ba yung pwede nateng isipin kung ito yung nakita niya.],
  [Valdeabella:], [What challenges or pitfalls should we be aware of in conducting this kind of research?],
  [Expert:], [Na you have to have thorough investigation also. I think lawakan niyo yung inclusion criteria. For example, not just a photo, you have to have like...],
  [Javier:], [Parang questions din po?],
  [Expert:], [Yes. Kase di mo naman maiinterview si patient eh di ba? But if you have like---may mai-input na siya like your demographics, occupations ganyan, medications that the patients is taking ganun. It would help to narrow down yung gusto mong ma-achieve na _[inaudible]_. You just don't look at the photo. If you can add other feature na can narrow down...],
  [Valdeabella:], [Next question. Are you aware of any reliable institutions, agencies, or organizations that provide clinical images or datasets of nail disorders suitable for research use?],
  [Expert:], [If it's just photos, I think this one or DermNet I think. Kase you're looking at photos eh. The one that's available on the web ha. Ngayon ito lang naiisip ko, DermNet. Kase the rest would be journals na eh kaya lang if you're just looking at pictures, I think okay lang. Syempre if you can get like journal access, mas okay din yun. PubMed ganun.],
  [Javier:], [Sa government po kaya?],
  [Expert:], [Ay di ko alam, _[inaudible]_.],
  [Valdeabella:], [Ayun po yung sinuggest nung isa pong nakausap ko po sa DOH gawa't wala daw pong dataset dito sa...],
  [Expert:], [sa local ha, but photos-wise wala kase even our society parang wala eh. What you have is a census pero _[inaudible]_ pictures.],
  [Valdeabella:], [Opo.],
  [Javier:], [Kapag mga text po kaya? Halimbawa mga excel ganun?],
  [Expert:], [Ano yun?],
  [Macapallag:], [Text-based po na data.],
  [Expert:], [Kung text, talagang journals like PubMed. Kaya langminsan may membership _[inaudible]_. May mga free pero merong hindi. But if gusto mo ng medyo reputable na---not sure if you have it here in the---we have journals but I'm not sure how frequent ang nail mo lalabas. This is what we have in our society of dermatology but yun nga, I am not sure how frequent may nail siyang lalabas, kase this would be...ano na siya eh. Medyo technical na to eh. Like all skin condition na to.],
  [Javier:], [Parang masyado pong specific yung nail?],
  [Expert:], [Oo, kung ina-narrow mo lang yung nail, baka medyo malula ka dito. Kase this is all ano lang---talagang systemic skin condition _[inaudible]_],
  [Valdeabella:], [So last question na po. Are you aware of any institutions, agencies, or organizations that provide datasets related to nail conditions and their correlation with systemic diseases?],
  [Expert:], [You should find it in PDS but yun nga, baka marami siyan kasama. Pero yes ganun, kase mas specific siya to ano talaga, skin conditions _[inaudible]_. You just check your sources, pero the safest syempre and most reliable is yung journals, not just like mga articles. You can also check AAD, American Academy of Dermatology just for _[inaudible]_. Baka meron naman sila nung mga photos lang. I think they have more resources available than our local societies when it comes to pictures.],
  [Valdeabella:], [Pag halimbawa pong nakakuha po kami ng dataset ng pictures sa ibang bansa, applicable po rin yun dito sa mga filipinos?],
  [Expert:], [Yes. I think ang mag iiba lang naman is how frequent you see the _[inaudible]_. Pero generally, _[inaudible]_.],
  [Valdeabella:], [That's all po.],
  [Expert:], [Ahh okay. Thank you!],
  [Researchers:], [Maraming Salamat po!],
)
