/* Consultation - 10/08/25 */

#grid(
  columns: (1fr, 3fr),
  row-gutter: 1.5em,
  [Valdeabella:],[Ma'am bale ito po yung sa model po.],
  [Ma'am Mia:],[Napacheck na kay Mark?],
  [Valdeabella:],[Opo.],
  [Ma'am Mia:],[Nasan yung application niyo for RC? Ayaw mo bang pirmahan ko? Bahala kayo kung ayaw niyo 'di wag. Oh game. Asan ako? Sino naggawa nito ? Sino nagsabi nito? _[points to matrix compliance]_ Yung eto, ako ba?],
  [Valdeabella:],[Ayan lang po yung nakalagay po dun sa papel po namin sa summary of recommendations.],
  [Ma'am Mia:],[Oo nga, ibig ko sabihin sinong nagsabi nito? Ako ba o ano?],
  [Valdeabella:],[Wala pong nakalagay dun sa ano...],
  [Ma'am Mia:],[Eh sige kung ano man, edi pipirma ako dun kung ano man. Dito muna sa ano, kung fully ano---yung datasets from experts---iisa-isahin ko para pipirmahan ko na sya ngayon. Okay na?],
  [Valdeabella:],[Opo.],
  [Ma'am Mia:],[Patingin nung corpora niyo. Yung corpora para siyang ganto, para siyang datasets. Kunwari, for every ano---sinong nagpasa? Ako na nga, titingnan ko para makita yung---si Valdeabella? Ikaw nagpasa nung ano?],
  [Javier:],[Ah nasa ano po, sa sheet po yung latest.],
  [Ma'am Mia:],[Sheet ka rin. Chos. De eto kako yung docu?],
  [Valdeabella:],[Ayan pa po ata yung dati pa po. Nasa CS Thesis Monitoring po yung latest.],
  [Ma'am Mia:],[Eto? Ah may latest ka? Huy pero dun niyo ilagay yung pinaka final kase dun ako magtitingin. Ay baliktad. Dapat dun---nagcomment ako dito tapos dito na yung final. Lipat niyo nalang ha, nasan na ko? Wala. O dito sa approved? Eto? _[referring to google sheet]_],
  [Valdeabella:],[Eto po dito po ma'am. Ah iba po palang ano yan.],
  [Javier:],[Thesis monitoring po, CS Thesis Monitoring.],
  [Ma'am Mia:],[Eto. Yung luma yan ih. Ah yung ano naten, yung pang subject. Anong section niyo?],
  [Valdeabella:],[Sa 4B po, pang apat po na...],
  [Ma'am Mia:],[Oo eto naman nakakapagbasa naman _[inaudible]_. Eto pang apat. Sige una, unahin naten ha. Kaso yung dataset niyo wala dito noh? Pero gusto ko siya naka format na ano---paano niyo nilagay yun? Yung corpora niyo?],
  [Valdeabella:],[Naka-ano po siya ma'am, sample ng mga images tas yung description.],
  [Ma'am Mia:],[Ganto lang, ganto? Try naten para mas ano yung corpora. Nagagalit si Mark na may mga nilalagay akong date. Pero pag magpepresent na tayo tatanggalin na naten yung mga dates. Ayaw na niya yung simpleng specific date. _[prompt perplexity to create a sample corpus]_. Ganto siya dapat oh. Parang ganun siya.],
  [Valdeabella:],[Kakasya po kaya yan ma'am sa papel?],
  [Ma'am Mia:],[Alin ba?],
  [Valdeabella:],[San po ba yan ma'am? Sa dataset po?],
  [Ma'am Mia:],[Dapat sa chapter 3. Oo. Yan na yung tinatawag nateng corpus structure kase dalawang part eh, yung image dataset niyo so ang magiging itsura niya..._[prompt perplexity to create a sample table]_. Gets niyo na? Eto yung part b. Kumbaga titingnan naten yung association niya tas meron siyang percentage. Tapos depende siya sa ano---ganyan yung dataset na sinasabi ko, ang tawag dun corpora. Corpus structure talaga siya.],
  [Valdeabella:],[Meron po kaming dataset, bale gagawin po namin siyang ganyan?],
  [Ma'am Mia:],[Yung ganto itsura niya. Alam niyo na naman kung paano i-prompt noh? So kunwari, during the presentation, para mas maliwanag, ganto gawin niyo. Eto yung objectives niyo, research objective. Ito yung dataset components niyo, eto yung data requirements niyo, tas eto yung verification processing. _[referring to the sample corpora]_.],
  [Valdeabella:],[Ma'am pwede po picturan?],
  [Ma'am Mia:],[Hindi icocopy paste ko nalang.],
  [Ma'am Mia:],[Yan lang naman hinahanap ko. Para siyang ano---copy paste ko na kaya lahat? Yan yung ano---eto ay---para di kayo mahirapan, diba ganyan naman talaga yung pinaka corp---ano yan, corpus structure. Kase yun lang naman hinahanap naten diba? Chapter 3 dapat yan tapos di ba eto _[points to part A of the sample corpus structure]_, di siya masyadong ano, description lang at source. Pero at least kita mo yung corpora niya, corpora structure.],
  [Valdeabella:],[Ah okay po.],
  [Ma'am Mia:],[So eto _[referring to the data requirements and processing specification table]_ ay para dito. Eto ay ipapagamit ko lang sa inyo para sa presentation para hindi magulo ang panel niyo o yung mga non-CS ano niyo. Kumbaga during your presentation, dapat ganyan, 'anong methods?' para malinaw, summary siya talaga. Tapos yung corpus structure niya eto sample niyan, ito yung sa fingernail. Dapat ganyan siya _[points to sample corpus structure]_. Tas specific siya, 'san galing?' tapos kung curated ganun. Eto kase di pa siya ano, kumbaga sample lang siya tas yung preprocessing na gagamitin niyo: augmentation [and other methods] kase eto na yung methods. Kung meron pa kayong mga inadd dyan na methods ilalagay niyo jan. So it should be presented in a table. Ito yung sinasabi ko sa inyong corpus structure.],
  [Valdeabella:],[Ma'am bale po ito pong mga to, present na po siya sa ano namin, sa paper. Gagawin nalang po namin siyang table?],
  [Ma'am Mia:],[Hindi mo siya gagawing table, ipe-present mo siya na mas comprehensive. Tapos, kunwari kung talagang ano---nakalagay dito kase sample size ano eh, di ba nag 80/20 kayo for testing? I-specific niyo na ang na-acquire niyo, ilang percent? Kase ano ha, sample lang to. Ang na-acquire niyo let's say ay 100,000. 80,000 dun ay galing sa...],
  [Valdeabella:],[Training?],
  [Ma'am Mia:],[Hindi, san ba galing yun? Synthetic? 'Sources from...' diba yun ang inano sa inyo ni Mark? Kase process na yun ih, yung kinuha niyo dun sa ano. Tapos yung isa ay 'acquired', 'curated'. Pag dinefine mo yung definition of terms sa curated, kayo ang nag feature sa definition of terms kase others would not understand that, tayo lang gumagamit nun ih. Sa dataset naman---so eto yung tinatawag naten na corpus structure. So dalawa yung sayo: isang labeled fingernail image set tapos yung isa naten ay kung ano yung sakit na pwede naten i-associate. Eto na yun _[referring to sample corpus structure]_. Tapos aralin niyo na para mag-ano. So eto yung references nung study. Pero dapat yung references ng study ay di lang siya basta source. Sige gawin naten to _[prompts perplexity to make the table more specific with one line of description about the references]_. Kase pag ganun lang, chaka. Di mo makukuha yung talagang ano---tas lalagay mo dito kung ano yung study tapos---gets nyo? Yan na yung corpora mo. Malinaw kung paano niyo siya i-present?],
  [Valdeabella:],[Opo.],
  [Ma'am Mia:],[Makikita naten yan sa chapter 3. Eto hindi naman _[points to sample data requirements and processing specification table]_. Sa presentation yan, baka malito kayo. Eto makikita naten sa chapter 3 _[points to sample corpus structure]_ pero again, sample lang to. ni-generate ko lang siya from your objective pero meron pa rin kayong ginawa na sobra pa dun objective naten. Like for example, eto ang ni-generate niya lang naman ay augmentation eh baka may iba pa kayong ginawa eh. Mas malinaw?],
  [Valdeabella:],[Ma'am bale lahat po yan sa data collection na section?],
  [Ma'am Mia:],[Yes, data preparation---data collection kase ito yun ih. Source, sample size... so inilalagay mo sa kanya kase---diba dito sa data collection, nagkukwento ka lang naman dito. Sa data collection kase nagkukwento ka pa lang niyan. _[inaudible]_, ganyan ganyan, ganun ganun, tas eto naglagay agad kayo dito pero yung dulong dulo niyan pak! Ayan dapat yun para introduction siya dito sa model generation or else ang gawin naten for example, sa dulo siya ng eto...kase yan din yun eh. Ay nako, heka lang. Ito'y ginagawa niyo na? _[points to code snippets in chapter 3]_. Pang result yan ih. Mali?],
  [Valdeabella:],[Ma'am bale ayan po yung kung paano namin ginawa yung systemic disease...],
  [Ma'am Mia:],[Oo pero may result na siya?],
  [Valdeabella:],[Wala---ano---yung code lang po kung paano po gumagana.],
  [Ma'am Mia:],[Nilagay mo pa rin yung code?],
  [Valdeabella:],[Opo.],
  [Ma'am Mia:],[Pag ganto ano siya, yung mismong code, hindi yung screenshot.],
  [Macapallag:],[Code po?],
  [Ma'am Mia:],[Code mismo. So lalagay mo siya ng figure kase isipin mo, paano mo makikita yan pagdating sa docu? Pag black niyan ano? Code siya ilagay mo nalang siya na---ang pag kunwari, sample ko lang ha. Pag nagcocode ka, gagamitin mo yung header na code. Ah wala palang option na code dito.],
  [Javier:], [Okay lang po yung ganyan karami? Lahat po yun ipapakita namin?],
  [Ma'am Mia:],[Kasi ie-explain mo yun ih. Your code was generated by you? Developed by you? Or galing siya sa black-box AI or what?],
  [Valdeabella:], [Halo po. Sariling ano tas pinapa improve po sa mga AI po.],
  [Ma'am Mia:],[Yun, dapat pati yung composition nung code. Kung ganto kakapal yung code mo sa cleaning or whatsoever kase yung cleaning naman automatic naman yun wala ka naman babaguhin dun,wala ka naman special code nun ih so iaano mo siya, ang gagamitin mo let's say, kunwari ito code, ang gagamitin mo nalang na format ay yung 'Intense'. Nakaganyan tas explain mo kunwari, etong code na to, color coded na pula, 'this was...' ganyan ganyan etong line na to. Etong line na to, ganyan ganyan, ganun ganun. Gets niyo? Oh picture. 'Intense' baka malimutan niyo. Kayo nanaman sample ko sa klase.],
  [Valdeabella:], [Yung sa color coding po, may parang guidelines na sinusunod po ba dun?],
  [Ma'am Mia:],[Wala naman, kunwari lang. Like for example---ang problema kase sa inyo nag testing kayo nang hindi niyo tinetake-down notes, hindi niyo dinodocument. Hindi niyo alam kung san yung pinag daanan ng code niyo ih. Dapat yun documented. Kunwari katulad nga ng sinasabi ko sa inyo, every time na---even data preparation nag code kayo. Diba, syempre alam ko naman galing sa GPT or what. Pero kumbaga anong effect niya? Tapos ano yung output niya? Dapat lahat yun inaano niyo. Even sa testing ng accuracy, lalo na sa data prep kase yung ang mahalaga, pinaka mahalaga dito preparation. Katulad nun yung augmentation niyo may sample kayo. Ini-screenshot niyo, tsaka dapat recorded lahat. Ngayon ganto ha, uulitin ko yung discussion ko. Lahat ng chapters 1-3, ito ang ilalagay niyo dito mga strategies tsaka methods. Lahat ng results sa 4. Dito ineexplicate, dinidiscuss mo siya kung anong strategy niya ganyan. Pwede siyang in table, pwede siyang---like for example, eto yung table tapos i-detailed niyo. Pero hindi yung napaka daming palabok. Pwedeng kunwari, procedure tapos paulit ulit na experimentation pero iniintroduce mo lang siya. Tapos pagdating ng 4, ipapakita mo yung result ngayon in figure kung ano yung naging result niya, ano yung mga ginawa niyo dito na pwede niyong i-mention na 'nag conduct din kami ng trial 1, 2, 3, 4 tas naging successful kami sa 5 pero nag try pa kami ng trial 6. So naging okay yung trial 5.' So yung 1, 2, 3, 4, 5 and 6, yung method nun makikita niyo sa chapter 3. Gets niyo na?],
  [Javier:], [Ma'am yung ganto pong format okay lang po? _[points code snippet presentation format]_],
  [Ma'am Mia:],[Pwede naman yan. Eh parang ganun din naman to ih. Yung pinakita ko sayo, parang ganun. Iha-highlight mo lang siya. Wala lang [indentation] or something pero yan din yun. Yung ganun tas aayusin niyo nalang. Basta naka ganto 'Intense Code'. Parang yung mga ano naten sa mga LMS ganun din naman tapos highlighted. Basta code ganun itsura niya.],
  [Valdeabella:], [Ma'am yung sa ganto po ba, halimbawa po, dito po kase _[points to data model generation section in the manuscript]_, dinocument ko pa rin po yung dati ko pong code eh kaso po'y hindi po siya scalable. So ang ginawa ko po, sa final setup ko po, nag implement na po ako ng OOP tsaka pang modularization.],
  [Ma'am Mia:],[Pero dapat hindi yan yung kunwari ano---vague pa siya eh, so dapat i-explain mo siya anong OOP, like specific. Kase ang 1-5 naten, kumbaga overview siya. Kung hindi siya kakasya, edi ilagay mo sa appendices. Kunwari yung mga codes na ginamit niyo or something. Tapos dapat labeled siya. Kung ganun yung sa intense code siya, eto yung code namin, eto yung ano namin, yun. Not naman the whole code, partitioned lang kase kailangan labeled pa rin siya. Kunwari yung code niyo ng data preparation, eto yung mga yun. Augmentation, eto yung mga yun. Pwede niyo ngang in a table eh, pwedeng ganun, pwede namang intense lang, deretsong discussion lang din. Pero ang pinaka mahalaga niyan sa dulo---ang algo analysis nag iintroduce palang naman kayo kase dun niyo mapapansin kapag algo---kunwari nag-aano kayo kaso ang mga ginagamit niyo kase panay pre-trained na eh kung tutuusin. Pero kung panahon namin na hardcore talaga siya, for every algo, iba ang data prep. Nakailang data prep kayo dito?],
  [Valdeabella:], [Ma'am marami din po, kada model po iba't iba rin pong hyperparameters. Nandito po siya sa training strategies po. So, bale sa---actually meron na din po kaming results, ilalagay nalang po namin...],
  [Ma'am Mia:],[Ilapat, kaya nga sabi ko sa inyo dapat yung 4 niyo may draft na. Kase dapat yung screenshot niyo dun nandun. So kunwari kahit ano palang kayo---kase ang gusto naten iincorporate ngayon sa objectives, kunwari yan, kung meron kayong ano, nandito na kayo, dulo na. Ito nalang kulang niyo, pero lahat yan, the rest, ganun ang idea ng research colloquium tas the rest wala na, meron ka ng 4 jan. Kase sa IT, chapters 1-3 talaga lang sila. Kumbaga wala pa silang kunwari meron yan design, chapter 1 and 2 dapat may result na siya. Pero tayo, dapat hanggang dulo, isa nalang, testing nalang ng accuracy. Testing naman naten ng accuracy, limited lang siya. Evaluate lang naman ng ano ih, di naman nagsasabi na may sakit na automatic eh. Parang magbibigay lang siya ng ano ih, parang _[inaudible]_ ng ipinresent. So yun, yung corpus overview, ilagay mo siya sa dulo nalang. Kase para siyang summary of lahat ng ginawa mo eh. So pwede mo siyang ilagay kase ang datasets talaga nakalagay yan sa...dapat nakalagay siya sa harapan pero since...talagang pati to nilagyan ah. Bakit pati yung zotero? Ah documentation and communication tools.],
  [Javier:], [Opo, hinati po namin.],
  [Ma'am Mia:],[Grabe, okay lang. At least, talagang ginamit naman natin siya. Before ng system architecture---itong system architecture pinapalagay ko siya sa 4.],
  [Javier:], [Pwede po kaya yan? Hinati ko po yung system architecture by layer.],
  [Ma'am Mia:],[Oo, walang problema. Lagay mo na to sa 4 kase result naman talaga siya. Kase yan yung pinagdedebatehan. Ako kase---parang nagrereact sila ngayon bakit daw pinapalagay ko sa 4 yung ano. Eh hindi naman siya method ih, result siya ih.],
  [Researchers:], [Tama, tama.],
  [Ma'am Mia:],[Nabuo mo siya nung dinevelop mo ih. So yun, kaya ang maganda, ilagay mo yan sa 4 kase ito method talaga yang testing eh, pero dito, ilagay mo dito, palitan mo, icopy-paste mo nalang dun---ako na nga lang. System overview siya ih diba? Instead na system architecture, system overview siya. Siya talaga yung overview. Potek UM yun. Ilagay mo sa ano yung iba. Ilagay mo yung...ito palit mo sa system overview mo. Tapos ang gawin mo, yung iba, dapat yung isa lang, yung pinaka context lang.],
  [Javier:], [Ah hindi po yung...],
  [Ma'am Mia:],[Oo, tapos yung the rest lagay mo sa appendices kase masyado na siyang ano, tapos dito isingit---diba testing---dito niyo ilagay yung corpus overview. Yun na yung corpora. Dito mo ilagay ang corpus structure. Ayan okay na to, wala na ko utang sa inyo. May tanong pa? Lagay ko pala sa gc.],
  [Javier:], [Yun po palang sa ano namin ma'am, sa bayesian inference, pwede po naming ipa-check sa statistician po ano po?],
  [Ma'am Mia:],[Sinong stat naten?],
  [Valdeabella:], [Si sir Victor Estalilla po.],
  [Ma'am Mia:],[Oo okay naman. Anong sabi ni sir Victor sa gawa niyo?],
  [Valdeabella:], [Di pa po kami nakakapagpacheck.],
  [Ma'am Mia:],[Yayabangin ko ih. Syempre ano yun ih. CS yun ih kaso math ang major niya.],
  [],[_[recording ends abruptly]_],
)
