#grid(
  columns: (1fr, 3fr),
  row-gutter: 1.5em,
  [Presenter:], [_[End of Presentation]_],
  [Ma'am Mia:], [San yung ano? sabi nyo dito clinic health data source.],
  [Presenter:], [Alin po?],
  [Ma'am Mia:], [Clinic data source. Local health agencies. Na-achieve ba yun o hindi?],
  [Presenter:], [Hindi po.],
  [Ma'am Mia:], [Contakin niyo to, yung ano ko. Nakakuha siya sa---si James Neil Mendoza. Nakakuha siya sa pinagtatrabahuhan niyang ospital. Yun nalang gawin niyong pang testing.],
  [Presenter:], [So ma'am ito po yung system namin.],
  [Ma'am Mia:], [Yung systemic diseases---ano lang siya---limited lang siya sa diabetes, cardiovascular, tsaka liver? Yung tatlo lang?],
  [Presenter:], [Hindi po. Sa isang biomarker lang po yun.],
  [Ma'am Mia:], [Ha?],
  [Presenter:], [Per classification po ng nails---halimbawa clubbing---Yun pong mga nabanggit niyo, sa clubbing lang po iyon, bukod pa po yung nail classifications.],
  [Ma'am Mia:], [Hindi, ang tanong ko lang naman, kung yun lang ang ica-classify naten.],
  [Presenter:], [Hindi po.],
  [Ma'am Mia:], [Ano pa? Eh kase eto---kayo chatgpt na chatgpt di naman wise yung pagkakaano niyo dito sa scope and limitation. Sino gumawa docu niyo? Eto nakalagay eh. Systemic diseases such as diabetes cardiovascular disease, tsaka liver.],
  [Presenter:], [Ma'am parang example lang po yan.],
  [Ma'am Mia:], [Anong example eh di naman naten mae-example yun? Kase eto si fingernail---oh yan---tatlo yan. Ang sabi niyo dito diabetes, cardiovascular, tsaka liver. May underlying pa yan bawat isa. May stages. Ang tanong ko lang sa inyo, dito lang sa tatlong to?],
  [Presenter:], [Hindi po.],
  [Ma'am Mia:], [San pa? Hindi tayo matatapos dito.],
  [Presenter:], [Ma'am halimbawa po sa pulmonary disease---],
  [Ma'am Mia:], [Pulmonary---kayo nagsabi nyan ha wala sa docu niyo. Pulmonary? Sigurado kayo? Kase for diabetes, may stages din yan. Meron din yang variety. Kase yun---sila ay---ano lang sila, parang---major---tapos---tingnan niyo ha, ang gulo nyo.],
  [Ma'am Laureen:], [Type 1, Type 2.],
  [Ma'am Mia:], [Varieties lang yun ih. Ang cardiovascular may coronary---yung CAD. May heart failure, may stroke, may PAD, may aortic. Gets nyo?],
  [Presenter:], [Opo.],
  [Ma'am Mia:], [Sa liver may hepatitis, fatty liver, cirrhosis, etc. Ibig sabihin, for every diseases, may mga list pa jan ng variety.],
  [Sir Mark:], [Baka yung kanila general lang ma'am. Kunwari cardio, yun lang. Tsaka ka magpapacheck.],
  [Ma'am Mia:], [So ibig sabihin general lang?],
  [Presenter:], [May mga specific din po.],
  [Sir Mark:], [Nails lang siya eh, di mo talaga siya makikita yung pinaka specific.],
  [Ma'am Mia:], [When it is not included in your docu, hindi niyo sasabihin yun. Dapat dito palang sa docu nyo---kaya nga tinitingnan ko yung scope and limitation niyo. Kumbaga general? Madedetermine niya lang yung common symptoms? Symptoms yun ih. Ngayon, do you have any theoretical framework that would correlate on the fingernail and then the systemic diseases? Kase dun ako titingin besides your CNN. Kase ang meron ngayon na study---kapag inaral niyo siya ng maigi---ang meron lang ay yung point A to point A. Fingernail and then nail diseases. Dapat nandun sa theoretical framework niyo yun. Gets nyo?],
  [Presenter:], [Opo.],
  [Ma'am Mia:], [Ngayon mabalik tayo dito. General lang siya? Hindi siya specific?],
  [Presenter:], [May specific po and may general.],
  [Ma'am Mia:], [Paano mo nasabi?],
  [Presenter:], [Sa iba po kaseng nail disease, may specific po talaga siya na kaabikat na sakit. Sa mga general naman po like clubbing---],
  [Ma'am Mia:], [Oo alam ko yun---sa heart---kase common knowledge na nga yun.],
  [Presenter:], [Tas sa---],
  [Ma'am Mia:], [Di ko alam kung nagkakaintindihan tayo dun sa sinasabi ko. Dun kase ako sa system niyo. Ang tinatanong ko, kung may capability siya. Kase oo kayo ng oo. Hindi niyo naiisip yung scope and limitation niyo. Kaya nga may scope and limitation. Hanggang december 2025 lang tayo. Kaya nga tinatanong ko sa inyo---merong specific---paano mo nasabing merong specific? In your document, eto lang nilagay niyo, general. Probability nga eh. Di nga prediction eh. Probability lang kayo eh. Paulit ulit, anong sabi mo kanina na paulit paulit niyong sinabi? "This will not give any medical recommendations. It will just provide probability." Diba? Mere forecast but not prediction. Oh sige continue. Kase your document does not---sino gumagawa ng document?],
  [Presenter:], [Kami pong tatlo.],
  [Ma'am Mia:], [Yan ang mahirap. Diba? Katulad nun objective palang---okay yung conceptual framework niyo pero di nagrereflect sa objective. Tas palagay ko di niyo rin masyadong pinag-aralan. Andun lang kayo sa tip ng iceberg. Andaming babasahin dyan ih. Palagay niyo ibibigay ko yan ng di ko pa nababasa? Dapat nga on your chapter 3---meron bang nakalagay dito? Di pa ako umaabot dun dahil yung chapter 1 palang---may mga images kayo? Wala akong makitang mga images dito na paano mo siya---dumaan pa sa chatgpt halatang halata document niyo. Di man lang nabago ih. Wala man lang ako makitang images dito that would tell na 'this is healthy,' 'this is correlated with this.' Kase for every curves, creases ng kuko---sa image meron yang texture diba Mark?],
  [Sir Mark:], [Oo.],
  [Ma'am Mia:], [Yun ang datasets nyo. Yun ang huhulihin niyo ih. Kase yung clubbing---eto yan---arc. Pero yung iba, creases. Eto oh, sample. Eto mismo yung diseases. Dapat may images kayo jan. Dito may discoloration, images kayo eh. So dapat ang dinidiscuss niyo samin ngayon...],
  [Sir Mark:], [May shape sila, may color...],
  [Ma'am Mia:], [Like for example nag augment kayo. Para makita ang alin? Na paninilaw? Darkening? Sa ibabaw ba o sa ilalim? Gets nyo?],
  [Presenter:], [Opo.],
  [Ma'am Mia:], [Yun ang detailed. Yun dapat ang pinag-aaralan niyo. Dapat binibigyan niyo kami ng images dito that would tell na 'ito' ay healthy. What does healthy nails looks like? Yan oh, yung lunula niya meron siyan certain measurement away from the tip. Diba? May ganun. So kung merong problema sa lunula mo, kunwari wala na yung white o wala na yung difference such as this, may something wrong talaga. Pag yung masyadong wide---dapat yun ang dinidiscuss niyo samin ngayon pagdating sa image preparation.],
  [Presenter:], [Okay po.],
  [Ma'am Mia:], [Wala akong makitang images on your chapter 3. Wala akong makitang theoretical framework na correlated sa fingernail that would tell us---yung nandun sa inyo ay yung mga previous work pero wala ako makita na correlated. Diba? Ibig sabihin, eto yung ginagawa nyo. You're doing that pero malayo sa documented niyo. Nandun palang kayo sa tip pero yung pinakasense niya---dapat nga ngayon eh "We use this augmentation para makita namin yung color, yung texture, yung creases, yung arcs." Oh ano ba sa nail? Ano ba dapat naa-identify mo dun na dataset? Meron talagang measurement yun eh. Sige discuss. Kase dapat ipakita niyo samin yung certain images na kung paano nyo...],
  [Sir Mark:],[Ang labo kase nung pinaka final output na gustong mangyari. Di mo pa alam kung ano talaga yung ia-identify mo. Ano yung output na makikita?],
  [Ma'am Mia:], [Ano yung algo niyo?],
  [Presenter:], [ResNet50 po tas---],
  [Ma'am Mia:], [ResNet---ano lang din yan...],
  [Sir Mark:],[Model na yun ih.],
  [Ma'am Mia:], [Pre-trained na siya ih. Transfer learning model na siya. Eto yung hinahanap ko sa inyo oh. Yung description. Dapat binigyan niyo kami ng datasets na ganyan. Sabi nyo annotated ih. So dapat meron jang clubbing---ilan dun na meron jan. Nasaan?],
  [Presenter:], [Nasa chapter 3 po.],
  [Ma'am Mia:], [Sige tingnan ko. Wala yung chapter 3 niyo mabilisang ginawa sa kung saan man. Tingnan niyo ang nilagay niyo dito ay yung experimentation niyo pero hindi yung description. Nag mention kayo dito ng Terry's Nail.],
  [Presenter:], [May nilagay po ako sa RRL na mga description po ng mga nail biomarkers.],
  [Ma'am Mia:], [Pero walang images dito. Wala siyang details sa chapter 3. You just mention it. Anong sense niya? What is it for?],
  [Presenter:], [Edi dapat po ay lagyan namin ng image sa---],
  [Ma'am Mia:], [Di ko alam sa inyo.],
  [Presenter:], [Opo, ganun po yung gagawin namin.],
  [Ma'am Mia:], [Kase yun yung chapter 3 ih. yun dapat yun ih---yung methodologies ih. Ang binigay niyo lang samin dito---nandito yung melanoma, kung ilan sila, pero wala naman description. Kase kung images tayo, ipapakita niyo samin yan kapag Acral Melanoma or Beau's line, or whatsoever, or healthy nail, dapat meron siyang image description dataset. Paano? Like for example, pink nail, kita mo pa yung blood, texture. Paano mo madedescribe ang nail? Ano ang attributes niya? Balik tayo sa attributes.],
  [Sir Mark:], [Mga features kase yun. Yung kailangan niyong i-extract sa image.],
  [Presenter:], [Parang idedescribe po yung---halimbawa kulay ng nails---pink pag healthy---],
  [Sir Mark:], [Imemerge mo yung mga data nun ih.],
  [Ma'am Mia:], [Yun kase yung inaano niyo eh. Nail plate, nail bed...],
  [Sir Mark:], [Yun nga yung kukunin mo, kung shape man o color. I-cocombine mo pa kase siya ih.],
  [Ma'am Mia:], [Eto nga oh, yung mga parts ganyan. Ganun lang siya kasimple. Wala akong nakita, lunula sinabi nyo, nail bed, cuticle. Kase eto yung ano niyo, shape, properties, yung lunula meron siyang certain measurement. Tapos yung sabi ko nga sa inyo, yung color and texture tapos yung shape, tapos yung arcs. Ganun. Dapat nandun yun, kase dun kayo mag iistart out. Kaya nga hinahanap ko sa inyo---dapat nga meron kayong theoretical framework about nails. Gets nyo? Dapat kita dun kase dun tayo nagwowork, sa attributes ng nails. For example, iisa-isahin niyo lang. Yung nail plate it can be atrributed to what? Yung lunula kapag may ganto, attributed siya saan? Saan manggagaling yun? RRL. Ayan oh, red lunula may be a sign of heart failure. yellow can be caused by antibiotic therapy. Ganun. Lahat icocorrelate niyo. Yun ang laman ng RRL niyo.],
  [Sir Mark:], [Anong na-identify niya?],
  [Presenter:], [Yung mga distinct features po ng nail.],
  [Sir Mark:], [Diba naka-label na sabi niyo, ano yung mga label?],
  [Presenter:], [Yung pangalan lang po ng ---],
  [Sir Mark:], [Pangalan ng sakit niyan nakarekta na?],
  [Presenter:], [Yung biomarkers lang po. Pangalan po ng nail feature.],
  [Sir Mark:], [Example ng nail feature.],
  [Presenter:], [Clubbing, pitting...],
  [Sir Mark:], [Yun yung naka-annotate?],
  [Presenter:], [Wala po siya nung sinasabi niyong shape...],
  [Sir Mark:], [Ahh, edi maidentify niya yung ano---may mga percentage yun?],
  [Presenter:], [Opo. Confidence level po.],
  [Ma'am Laureen:], [Tingin nga, sige na, huwag niyo ng register register, deretso na dun sa ano, tingnan naten kung ano na yung system niyo. Kase yung sa docu niyo eh. parang di na _[inaudible]_ yun.],
  [Sir Mark:], [Isa pa yun sinabi naman ng title yan ih. Yung lawak niyan ih. Specific talaga? Di matatapos _[inaudible]_ kaagad yun. Yung feature extraction nila malupit dapat yun ih.],
  [Ma'am Mia:], [Eh general lang naman yung diseases nila ih.],
  [Sir Mark:], [Sabi kanina di ba may specific.],
  [Ma'am Mia:], [Kaya nga pinipigilan ko kayo, masyado kayong magaling ih.],
  [Sir Mark:], [Kase di ba sa talampakan, maaano mo lang kung liver, heart, diba may ganun yun, kung san point. Sa ganto din, meron din. Kunwari dito, sa kidney. Edi dun ka mag aano.],
  [Presenter:], [_[Showing the system.]_ So ayun po, pag halimbawa pong---eto po yung classification mismo nung nail. ],
  [Ma'am Laureen:], [Paano nila nakuha yung confidence level?],
  [Presenter:], [Sa model po mismo yun.],
  [Ma'am Laureen:], [Edi na-train na yan?],
  [Presenter:], [Opo.],
  [Ma'am Laureen:], [Ano pang gagawin niyo kung na-train na yan?],
  [Presenter:], [Kami po yung nagtrain.],
  [Ma'am Laureen:], [Ahh.],
  [Presenter:], [Eto po yung mga linked systemic diseases niya. Sa acral lentiginous melanoma po, yung mga possible na related diseases niya ay eto _[inaudible]_. Sa nutritional deficiencies naman po, pwedeng halimbawa---protein deficiency, vitamin d deficiency. Ayun po. Relate din po siya sa HIV or AIDS.],
  [Sir Mark:], [Di ba papakita niyo yung dataset diyan?],
  [Ma'am Mia:], [Sana naman yung explanation niyo jan katulad nung HIV ay yung educational. _[inaudible]_],
  [Sir Mark:], [Patingin nga nung annotated. Parang yung isang buo kase ih. Isang buo yung ni-label.],
  [Presenter:], [_[Showing the dataset.]_ So eto po yung mga labels. Bale sampu po yan. Beau's line, blue finger, clubbing, healthy nail, koilonychia, muehrcke's lines, onychogryphosis, pitting, tsaka po terry's nail.],
  [Sir Mark:], [Saan yung inannotate?],
  [Presenter:], [_[Showing the dataset.]_ Ayan po yung training set. Augmented po.],
  [Sir Mark:], [Ahh ayun. Naka rekta na pala siya. Naka square nalang yung ano niyo eh.],
  [Ma'am Mia:], [Kaya nga. Ano pang pang annotate niyo dyan?],
  [Sir Mark:], [Hindi niyo nga makikita yung sinasabi niyo.],
  [Ma'am Mia:], [Eh pano kung nail disease lang talaga siya?],
  [Presenter:], [Pano pong nail disease lang?],
  [Ma'am Mia:], [Di ko alam sayo. Tanong ko ibabalik mo saken nakakabwisit kausap. Square lang siya ih.],
  [Sir Mark:], [Hahanapin nya lang talaga.],
  [Ma'am Mia:], [Io-augment mo talaga ih. Kunwari yung curves and creases, paulit ulit ako.],
  [Sir Mark:], [Labeled lang talaga siya. Hindi siya ano... Pag ganyan kaseng more on labeled, cinocompare niya lang.],
  [Presenter:], [Para pong halimbawa sa isang image, nakalagay sa CSV yung file path tas nandun po yung mga description?],
  [Ma'am Mia:], [Hahanapin niyo lang yung ka-image niya. Pero wala siyang feature extraction.],
  [Sir Mark:], [Hahanapin niyo lang yung features. Labeled yun ih.],
  [Ma'am Mia:], [So dapat meron kayong maeextract na feature. Kaya nga tinatanong ko yung attributes.],
  [Sir Mark:], [More on naka pre-trained kase sila ih. Hindi na kayo nag _[inaudible]_],
  [Ma'am Laureen:], [Patingin nga nung healthy nails.],
  [Presenter:], [_[Showing the healthy nails dataset.]_],
  [Ma'am Laureen:], [Healthy pa yung 99? Papano mo nasabing healthy? Yun yung tinatanong ni ma'am Mia.],
  [Ma'am Mia:], [Hindi kase naka-image lang siya, pero pag image kase---paano niyo nadetect na healthy? Ano yung mga attributes?],
  [Presenter:], [Ma'am yung mga attributes po ay na-learn na po nung---],
  [Ma'am Mia:], [Kaya nga. Ano pang pag-aaralan naten eh naka-square lang siya? Ibig sabihin, nalearn na siya? Tapos ang ginamit niyo pa pre-trained. Bakit pa siya naging thesis naten? Tas yung annotation niyo pa pa-square lang. Kumbaga napakababaw lang talaga. Gets mo? Oh sige mag picture kayo ngayon ng kuko niyo tas tingnan niyo jan. Tas kumuha kayo ng isang may hepa tas picturan niyo jan. Kase dapat ieexplain niyo samin yun ih. Katulad nung 99, visibly kung kami magjujudge nyan hindi siya healthy. Kase mukha siyan ano---visible eye yan. Di mo nga lang kung kuko yan o castañas ih. Diba? Kaya tayo gumagawa ng AI, yung hindi nakikita ng naked eye. Magkitaan tayo ngayon oh, "Ano yung ano mo oh" edi magjujudge ka lang dahil mababaw lang yung pananaw mo tungkol dun.],
  [Ma'am Laureen:], [Nakalagay naman kase dito sis, five state-of-the-art.],
  [Ma'am Mia:], [Ewan ko nga, super chatgpt nga yung document eh. Walanjo naman kayo. Parang nag eexpect ako ng more sa inyo. Yung chapter 3 niyo mukhang kagagawa lang nung bagyo tapos binagyo din siya. Wala man lang ako makita ditong graphs o ano lalo sa algo analysis. Bakit kayo nag came up with the algorithm na ganun lang, ganyan lang. Tingnan ko nga tong chapter 3 ng pinya. Tamo oh kahit tong pinya meron silang explanation kung ano yung MobileNet, DesNet, oh na-explain nila.],
  [Ma'am Mia:], [Maggegrade na ba kayo? Hindi o oo? Yan din ang sinample ko sa kanila gamit ang google lens. Di ka maggegrade? Ako nga pwede ko na i-70 to ih. Ano?],
  [Ma'am Laureen:], [Edi redef.],
  [Ma'am Mia:], [Kase 9:20 na, andami pa nung sila.] ,
  [Ma'am Laureen:], [Maguupload kayo ng picture tas iu-upload for comparison?],
  [Ma'am Mia:], [Syempre magbibigay lang yan ng ano niyo. Nakita mo chapter 3?] ,
  [Sir Mark:], [Yung dataset nila halo eh. May ibang ethnicity.] ,
  [Presenter:], [Nadedetect naman po yung distinct feature ng nail so ang iniisip ko pa ay pedeng sa user profile na rin po mag derive. Kahit ano naman pong ethnicity ay iisa lang po yung itsura nung---halimbawa po is melanoma, iisa lang po itsura sa iba't ibang ethnicity. Iba lang po yung rates nung pagkuha ng systemic diseases.],
  [Sir Mark:], [Yun nga iba pa rin.] ,
  [Presenter:], [Pero yung sa classification po ng nail iisa lang po.],
  [Sir Mark:], [Isa lang naman talaga sa lahat. Isa lang naman yung nail ih. Kaso nga may difference pa rin sa ethnicity.] ,
  [Presenter:], [Base po dun sa nainterview namin an expert ay mas nagpapabor daw po kapag sa mga hobby. Yun daw po yung mas nakakaapekto sa mga nail classification. Yun daw po sa mga ethnicity ay parepareho lang daw po ng itsura. Halimbawa po sa afro, kaya daw po tumataas yung melanonychia kase po yung environment po nila ay mas prone sa sakit na yun.],
  [Ma'am Mia:], [Ano na grade niyo?] ,
  [Ma'am Laureen:], [Redef.],
  [Presenter:], [Thank you po.],
)
