/* Consultation - 10/07/25 */

#grid(
  columns: (1fr, 3fr),
  row-gutter: 1.5em,
  [Macapallag:], [...eto yung sa data ano namin sir, yung nacurate na dataset dun sa _[inaudible]_ para makapaggawa ng bayesian inference. Ito po yung mga columns. Ito yung mga main _[inaudible]_ na kailangan namin sir. Yung $P("Nail" | "Disease")$, yung mga priors, tas eto yung priors na may disease...],
  [Sir Mark:], [Yan na yung mga underlying condition?],
  [Macapallag:], [Opo sir, then ito po yung sa _[inaudible]_.],
  [Sir Mark:], [Ano nga? Melancholy, yuun? Ilan yun?],
  [Javier:], [32.],
  [Macapallag:], [31.],
  [Sir Mark:], [Dami.],
  [Macapallag:], [So ito po yung sa inference namin sir. Yung una po naming phase, kukuhanin po namin dun is yung...],
  [Sir Mark:], [Patingin nga nung taas. _[referring to the bayesian inference code.]_],
  [Macapallag:], [Ito po yung lahat ng sa model evaluation po namin sir.],
  [Sir Mark:], [Hindi, yung sa visualization.],
  [Macapallag:], [Eto po sir. Kumbaga ito po yung kakailanganin naming values bago kami magkaron ng inference para masabi yung [systemic] disease na associated dun sa na-scan na image. Ito po yung confidence values then ito po yung code para sa inference namin. Ang mangyayari po dito sa pipeline namin, yung confidence score na nakuha dun sa model namin, papasok po dito sa inference pipeline and ica-calibrate po namin gamit yung confusion matrix. Ito po yung confusion matrix na pinagbasehan namin, galing mismo siya sa model directly. So ibabase niya po dun yung mga true label and mga predicted label. Mag-iiscale po siya dun sa ano namin, dun sa inference pipeline na---],
  [Sir Mark:], [Naandito na lahat yun?],
  [Macapallag:], [Ang alin po sir? Kumpleto na---],
  [Sir Mark:], [Yan na lahat yun noh?],
  [Macapallag:], [Opo, tas eto po yung phase one namin, eto yung phase two dun sa magiging system namin sir. So halimbawa, eto po yung nakuha naming confidence score dun sa model pagka-scan ng image---eto nga po, ang nadetect niya is may koilonychia, then ang mangyayari po jan is ica-calibrate po namin gamit yung nakuha dun sa confusion matrix, eto po yun. ii-scale niya po dito yung mga nakuhang confidence kung bakit---ica-calibrate niya para---since yung mga raw confidence score is hindi po siya fully accurate, around 80% lang po. ii-scale po namin yan para makuha yung mga softmax.],
  [Sir Mark:], [Ilan ba yung datasets niyo jan?],
  [Macapallag:], [Dun sa na-curate po namin is around 31 po, yun po yung sa lahat ng ten classes po...],
  [Sir Mark:], [Hanggang 36 din yun. Sabagay.],
  [Macapallag:], [Then after ng calibration, magkakaron po kami dito ng pag [cocompute] na po namin ng ano---based sa confusion matrix, then---],
  [Sir Mark:], [Patingin nga ulet nung matrix.],
  [Macapallag:], [Eto po yung confusion matrix---],
  [Sir Mark:], [Ah yan din pala yung sa taas.],
  [Macapallag:], [Tas eto po yung---],
  [Sir Mark:], [Patingin nga ulet nung sa baba. Mas nadadalian akong tingnan to. Puro zero naman dulo.],
  [Macapallag:], [Pag ite-testing namin sir, eto pala yung---],
  [Sir Mark:], [Ang galing naman nun, zero na dun.],
  [Macapallag:], [...prototype ng---],
  [Sir Mark:], [Bat antaas masyado?],
  [Valdeabella:], [Sir alin po?],
  [Macapallag:], [Halimbawa ito yung input na nakuha namin dun sa mismong model, dun sa confidence score. Eto nga, 99.62% na may koilonychia then may 28% so yung gagawin po namin dun sa system namin sa may UI, mag aask po kami nung input ng user para sa kanilang gumamit. Halimbawa male yung gumamit then 21 years old, ito po yung kalalabasan. So dumaan po itong mga result na to sa calibration muna nung confusion matrix namin para hindi siya agad maggagawa ng conclusion na tama. So ang kinalabasan po is more accurate than pag wala sa calibration. Ayan po sir, ang sinasabi po nung 99.62 na koilonychia is meron po siyang possibility na---],
  [Sir Mark:], [San niyo nakuha yung attributes na yun? Yung sex and age? nakaka affect yun?],
  [Macapallag:], [Opo sir. Sa literature po kami nagbase para---ano yung mga kailangan na variables.],
  [Sir Mark:], [Latest na yung mga ano niyo, literature na pinagkunan?],
  [Macapallag:], [Yes po sir.],
  [Javier:], [Naka cite naman po yung---],
  [Sir Mark:], [Dati kase puro image lang kayo eh. May ano na kayo, text.],
  [Macapallag:], [Eto yung pangalawang ano namin sir, dataset. Yung una is pang train ng model, tas eto yung sa bayesian inference.],
  [Sir Mark:], [Nag feature engineering kayo? Ilang percent yun? Yung ganto, yung sa sex tsaka sa age. Yung importance nun.],
  [Macapallag:], [Ang computation po jan sir, ang kailangan lang po namin is yung $P("Disease")$ or yung priors na may disease yung _[inaudible]_ nung specific na condition na yun. Then yung sa $P("Nail" | "Disease")$---],
  [Sir Mark:], [Edi hindi niya makukuha pag ano, yung mga acquired?],
  [Macapallag:], [Kumbaga enhancement lang po siya, enhancement po yung ano niya, demographics. Pang analysis din po siya, sensitivity analysis para makakuha pa ng accurate results ganun sir.],
  [Valdeabella:], [Bayesian---],
  [Sir Mark:], [Ilan nga yung percentage niya? Yung features niya? Yung importance level niya?],
  [Valdeabella:], [Ah yung parang distribution po ng male at female?],
  [Sir Mark:], [Oo. Eto, yung dalawang age and sex tsaka age.],
  [Javier:], [Kung gaano nakakaapekto po?],
  [Sir Mark:], [Diba yung sa feature engineering, ilan yung ano niya, percentage?],
  [Javier:], [Kung gaano po nakakaapekto yung---],
  [Sir Mark:], [Kase akala ko puro image lang gagamitin niyo eh.],
  [Valdeabella:], [Sir yung parang kung gaano po katimbang po yung dalawang feature---],
  [Sir Mark:], [Oo, yung percentage niya dun sa output. Sa features, feature engineering, sa pipeline din yan ah.],
  [Macapallag:], [Opo sir.],
  [Valdeabella:], [Sir, bale ang gamit po namin ay bayesian inference lang po mismo. Hindi po machine learning.],
  [Sir Mark:], [Ahh.],
  [Javier:], [Hindi po siya AI model.],
  [Macapallag:], [Combination po siya ng _[inaudible]_. Yung unang phase po namin, yun po yung AI namin. Dun po kami gumawa ng mga training disease. Dito lang po is bayesian inference, computation para makakuha ng probabilities.],
  [Javier:], [More on calculation lang po lahat yun sir.],
  [Sir Mark:], [Yung binibigay nung dataset na yun?],
  [Researchers:], [Opo sir.],
  [Valdeabella:], [Base po lahat yan sa literature na na-curate po namin.],
  [Sir Mark:], [Ang naisip ko kase, kung icocombine niyo siya, yung mga image na nakuha niyo wala namang age at sex yan.],
  [Javier:], [Kaya po---],
  [Sir Mark:], [Sige, ano yun?],
  [Valdeabella:], [Sir bale po jan, halimbawa, tapos na po yung classification naten, halimbawa, na-rule out na beau's line siya, anong tyansa niyang magkaron ng mga sakit? So eto po yung mga pwede niyang sakit.],
  [Sir Mark:], [Nalito tuloy ako dun.],
  [Valdeabella:], [Kase pag ano po eh, pag halimbawa po sir, beau's line yung nakuha niya, isang indicator lang po yung nail eh. Wala pong halos sure na indicator ng disease mismo, so naka-rule out po jan lahat nung mga pwedeng possible na diseases.],
  [Sir Mark:], [Edi magkahiwalay siya?],
  [Macapallag:], [Opo, two piece po yung ano namin. Classification and inference.],
  [Valdeabella:], [Bayesian inference.],
  [Sir Mark:], [Naguluhan pa ko dun ih, pinakita niyo pa yan. Kase paano kasi yun? Eh diba yung na-train niyo kase, yung image. Eh wala namang---image lang kasi siya ih.],
  [Macapallag:], [Opo sir, kumbaga, eto is naka-map lang po dun sa possible na...],
  [Valdeabella:], [Bale pag tapos ng classification, may inference na po sir base sa literature.],
  [Sir Mark:], [Edi parang ano, nag probability kayo dun sa probability? Ganun ang nangyari?],
  [Valdeabella:], [Sa confidence po nung model. Halimbawa, dito po sa example na to, confident siya na koilonychia yan, edi sa koilonychia po siya magbabase dito sa dataset.],
  [Macapallag:], [Kumbaga, weighted yung pag-iiscale niya dun sa mga probabilities, hindi po siya fixed.],
  [Javier:], [Parang cinoconsider niya rin po yung confidence level sa calculation. Kung mas mababa po yung confidence level, mas mababa din po yung probability.],
  [Valdeabella:], [Yan po sir, etong koilonychia, eto po yung mga pwedeng maging---],
  [Sir Mark:], [Edi ganun nga yung logic niya? Nag probability dun sa ano?],
  [Macapallag:], [Opo sir.],
  [Sir Mark:], [Although ayun nga, mataas naman yung confidence level, kase probability pa rin siya eh, tas nagprobability ka pa rin dun.],
  [Valdeabella:], [Opo. Bale, for proof of concept po sir, so ayan pwede pa po yan ma-update in the future kase po bayesian updating po kami eh. So habang padagdag ng padagdag ng data, mas ano...],
  [Javier:], [Mas nagiging accurate po yung---],
  [Valdeabella:], [Kase sa ngayon po kasi sir, limited lang din po yung data sa disease given nail sir. So limited lang lalo na po sa local, limited lang din po.],
  [Sir Mark:], [Ilan yan?],
  [Macapallag:], [32...],
  [Javier:], [32 yung nasa documentation eh.],
  [Sir Mark:], [Yan yang---ah yan yung kanina?],
  [Valdeabella:], [Mga 33 na literature po yan, hiwahiwalay sir.],
  [Sir Mark:], [_[checking nail feature count in the dataset]_],
  [Valdeabella:], [Pwede pa po yan madagdagan.],
  [Sir Mark:], [Ano to? Chronic ano to?],
  [Valdeabella:], [Chronic Renal---],
  [Sir Mark:], [Ah yan pala yun. Kahit nga may ano ih, lagyan niyo nalang ng simpleng computation ih. Diba for example, blue finger, 50/50 yung chances or yung probability na yun. Diba nadetect mo yung sa features, tas lalagyan mo na yun ng mga probability.],
  [Javier:], [San po kaya kami kukuha ng _[inaudible]_ sir?],
  [Sir Mark:], [Mahirap kasi dito ano ih, health kasi to ih, kaya ang hirap makialam ih, hindi ko din naman ano yan.],
  [Valdeabella:], [Kaya po yung samin, estimates lang po sir base sa prevalance.],
  [Sir Mark:], [_[inaudible]_ parang parehas.],
  [Macapallag:], [Opo pareho lang po yan.],
  [Sir Mark:], [Eh bakit ganun?],
  [Macapallag:], [Naano lang po yung casing pagta-type.],
  [Javier:], [Ibang literature po yan.],
  [Sir Mark:], [Hindi kayo nag preprocessing dito, bat nakalusot yon?],
  [Macapallag:], [Nakaano na po yan sir, nao-auto detect na po yan sa script, yung casing. Kumbaga naka lower case.],
  [Sir Mark:], [Eh nagkaron pa siya ng ano ih, ng point. _[inaudible]_ psoriasis yun? Terry's...ano yun terry's nail?],
  [Valdeabella:], [Opo.],
  [Sir Mark:], [Galing pa sa ano ih, may question mark ih.],
  [Macapallag:], [Hindi po support encoding sa...],
  [Valdeabella:], [Sir naka OnlyOffice.],
  [Sir Mark:], [Clubbing...],
  [Valdeabella:], [Bale ganun po yung approach namin sir, base po sa prevalance po, bayesian.],
  [Sir Mark:], [Okay na naman siya, nagulo lang ako sa dinagdag mo pa. Kase parang okay na yung sa image eh, nag dalwa kasi ih.],
  [Valdeabella:], [Yung sa image po sir ano ih, classification lang po siya nung nail mismo ih.],
  [Javier:], [Wala pa po nung mga systemic diseases na naka-connect],
  [Sir Mark:], [Pero dun siya naka-relate talaga sa ano, sa dalwang yun na attributes?],
  [Macapallag:], [Opo, interconnected po yun.],
  [Javier:], [Tsaka yung mga nababasa rin po naming study ay hanggang ano lang po ih, classification lang.],
  [Valdeabella:], [Opo, wala po silang inference kung anong systemic disease.],
  [Sir Mark:], [Sa doctor yun galing? Yung ganun?],
  [Macapallag:], [Mga medical sites sir.],
  [Javier:], [Yung mga pinagkuhanan po namin is literature.],
  [Valdeabella:], [Bale yan na po yung pang proof of concept po namin sir. So pwede pa po yan mag improve as ano---mas maging available---],
  [Sir Mark:], [Ilan yung mga studies na nakita niyong ganun?],
  [Macapallag:], [Ano po yan sir, multiple studies per entries. Hindi po siya limited para ma-confirm po namin yung mga values din.],
  [Sir Mark:], [Kase ang laki ng effect niya nung dalawang yun.],
  [Valdeabella:], [Alin po?],
  [Sir Mark:], [Yung dalwang attributes na yun. Dun mo talaga siya maca-classify. _[inaudible]_, okay na nga ako dun sa una. Napakita niyo na kay ma'am Mia?],
  [Valdeabella:], [Hindi pa po.],
  [Sir Mark:], [Ngayon ang checking ni ma'am?],
  [Javier:], [Ngayon ba o sa wednesday?],
  [Almario:], [Bukas.],
  [Researchers:], [Bukas po.],
  [Sir Mark:], [Okay na kase sakin to ih.],
  [Valdeabella:], [Ano pong marerecommend niyo po sir?],
  [Sir Mark:], [Hindi na ako magrerecommend ih. Okay na.],
  [Valdeabella:], [Okay na po ba to sir?],
  [Sir Mark:], [Oo, yung sa image kasi mataas na naman yung ano nun ih. Baka masisira pa yung ih pag ginalaw niyo pa ih.],
  [Javier:], [Sa statistician po kaya sir? Pwede po kaya namin ipakita yan sa statistician sir para lang ma---],
  [Sir Mark:], [Hindi ba---sinong stat niyo?],
  [Valdeabella:], [Si sir Victor Estalilla po.],
  [Sir Mark:], [Wala yun dito ih.],
  [Valdeabella:], [Sa CAS yun ih, sa CAS.],
  [Sir Mark:], [Hindi ko alam kung kelan, bukas o thursday. I-chat niyo, nag-aano naman yun, nagrerespond. Tanong niyo yung pang evaluate din, baka may marecommend siya.],
  [Javier:], [Ipapa-check rin po namin yung computation kung valid?],
  [Sir Mark:], [Oo, stat yun ih, tas yung mga testing plan. Sige okay na sakin yung inyo.],
  [Researchers:], [Thank you po sir.],
)
