/* Consultation - 10/13/25 */

#grid(
  columns: (1fr, 3fr),
  row-gutter: 1.5em,
  [Sir Victor:], [...ano?],
  [Javier:], [Opo, kaso ang problema po is limited...],
  [Valdeabella:], [Oo, limited lang po yung data kaya sa literature po kami kumuha ng mga ano. Yung mga prevalence nalang po kinuha namin.],
  [Sir Victor:], [Kaya nga eh, mahirap nga.],
  [Javier:], [May kopya ka ng sample dataset? Papakita naten kay sir.],
  [Macapallag:], [Anong sample?],
  [Javier:], [Yung mga literature ano...],
  [Macapallag:], [_[inaudible]_],
  [Sir Victor:], [So ano pa rin kayo ano? Oo, masyado pa rin dependent sa ano noh? Dun sa theoretical, hindi dun sa mismong empirical na data. Diba halimbawa pag nag deep learning tayo diba? Halimbawa yung mga neural networks, meron tayong training dataset na alam niyo na kung ano yung totoo diba?],
  [Javier:], [Opo.],
  [Sir Victor:], [Oh halimbawa eto may mga cancer to. Isang libong cases na alam niyo nang may cancer, isang libong cases na walang cancer ano? Isasalpak niyo yun dun sa algo niyo, okay? Tas ipepredict niya, nung algo---whether deep learning algorithm yun or some other. Ipe-predict niya based on kung ano yung nakita niyang mga symptoms. Eh alam niyo naman yung observed value; Ito isang libo may cancer, ilan dun yung tama yung ano niya? Ito walang cancer, ilan yung tama? Maca-calculate niyo yung accuracy ng algorithm. Sa inyo ay paano ang pagcacalculate ng---gaano ka-accurate yung isang algorithm?],
  [Valdeabella:], [Yung algorithm po namin sir sa ano, classification po siya ng nail. Bale yung sa inference po namin ng systemic disease eh bayesian lang po siya.],
  [Sir Victor:], [Hindi, ano tayo, simplehan naten, bababawan naten ano? Paano mo ica-calculate kung gaano siya ka-accurate? Halimbawa neural networks, it's either tama or mali siya, oh edi maca-calculate mo yung accuracy. Sayo?],
  [Valdeabella:], [Sir ganun lang din po. Bale ico-compare lang po sa ground truth yung ano...],
  [Macapallag:], [Via evaluations.],
  [Sir Victor:], [Eh kaso sinasabi niyo nga eh probability. Dapat mag desisyon siya kung ano talaga para malaman niyo kung accurate or not accurate. Kung ang ibibigay niyo ay probability, pano yun? Pano niyo macacalculate yun based on probability?],
  [Javier:], [Pwede po kayang may threshold po na ano...],
  [Sir Victor:], [Di ko nga rin ano yan ih.],
  [Javier:], [Kung lalampas po ng 70%...],
  [Sir Victor:], [Hindi ko alam ih kung pano pagka ganun.],
  [Valdeabella:], [Yung sa...yung ano po sir, halimbawa po, kung ano po yung pinaka mataas na confidence, ayun na po yung label sir.],
  [Sir Victor:], [Eh kaso meron kang true value ah, yung totoong kaso. Halimbawa, ulet. Halimbawa, pinepredict mo kung may cancer ako noh?Based on symptoms. Meron kang ganung algorithm. Alam mo na may cancer ako halimbawa, ang sabi ng algorithm mo, 'itong si sir Victor, merong 75% probability na meron siyang cancer'. Ngayon, alam niyo yung true value, yung true situation meron akong cancer. So, gaano ka-accurate yung algorithm na nagsasabi na meron akong 75% na probability na meron akong cancer? Sabi mo, 'sir, pwede ba yung threshold?' Yun ang di ko na alam kung pano.],
  [Javier:], [Parang kailangan po kasi talaga naming probability kase sabi po samin, pag deterministic daw po is parang kami na yung nagda-diagnose which is hindi po namin trabaho, trabaho na po ng doktor yun.],
  [Valdeabella:], [Bale yung output po namin ih prevalence po nung sakit kung meron kayong gantong kuko. So ano pong---],
  [Sir Victor:], [Kaya nga eh, anong ano nun? Edi wala kang way na macalculate yun? Wala kang ganung dataset na pagkukumpara? Pagkukumpara mo yung sagot niya, yung prediction niya dun sa totoong ano.],
  [Valdeabella:], [Kase po pag halimbawa po'y ano, pag ganto ang itsura ng kuko niyo, hindi siya laging ano, hindi siya sure na ganto yung sakit mo. Bale magba-branch out branch out pa po yun depende sa patient history, depende po dun sa ano...],
  [Javier & Macapallag:], [Demographics.],
  [Valdeabella:], [Isa po yun sa limitations po ng thesis po namin. Hindi po kami magda-diagnose ng pasyente so---],
  [Sir Victor:], [Hindi, ganun din naman eh. Kahit dun sa mga---sige, simpleng prediction ng mga---oh sige, random forest, diba meron kang parang training set diba?],
  [Valdeabella:], [Opo sir, sa ganun po'y ano---],
  [Sir Victor:], [Tapos pinepredict ng ano kung ano dapat.],
  [Valdeabella:], [Regression model na po yan sir, hindi po kami gumamit niyan. Bale samin po'y computation lang talaga, di po kami nagtrain ng inference para sa ano.],
  [Javier:], [Bale dalawang phase po kase yung ano namin.],
  [Sir Victor:], [Ulet, anong algorithm niyo?],
  [Valdeabella:], [Ito po sir.],
  [Sir Victor:], [Anu-anong limang algorithm?],
  [Valdeabella:], [Sa CNN po sir, una po classification ng nail. So ayan po, halimbawa ganyan po itsura ng kuko niyo, so healthy nail na po siya. Mula sa healthy nail, anong tyansa na meron kang gantong sakit?],
  [Javier:], [Tapos---],
  [Sir Victor:], [Kaya nga, ang tanong ko, pano niyo...anong ano? Saan nakabase yung data?],
  [Valdeabella:], [Dito po sa ano sir, sa dataset po.],
  [Sir Victor:], [Eh di ba pagka ganyan, halimbawa neural networks gamit niyo, dapat marami kang ganito.],
  [Valdeabella:], [Opo, test set na po yan sir, tinetest na po.],
  [Sir Victor:], [Oh tapos alam niyo yung sakit nitong mga to?],
  [Javier:], [Opo, may label na po.],
  [Sir Victor:], [San kayo nakakuha ng halimbawa isang libong ganyan?],
  [Valdeabella:], [Sa online po sir, sa Roboflow.],
  [Sir Victor:], [Meron kayo? Ganun kalaking data?],
  [Macapallag & Valdeabella:], [Opo.],
  [Sir Victor:], [Yun yung tinatanong ko diba? Edi nacacalculate mo yung accuracy.],
  [Javier:], [Yun pong sa classification po. Pero yun pong phase 2, wala po kaming ginamit na AI model dun.],
  [Macapallag:], [Kumbaga computation, bayesian inference.],
  [Javier:], [Pure computation lang po talaga.],
  [Valdeabella:], [Oo. Ito po ba yung tinatanong niyo po sir?],
  [Sir Victor:], [Hindi, yung pinaka algorithm niyo, neural networks? Meron kayo? Isa yun?],
  [Valdeabella:], [Oo, CNN na po yan sir.],
  [Sir Victor:], [Oh kaya nga. Tandaan niyo regression---yung underlying mathematics nun napakalaking regression model nun. Pag cinonnect mo yung mga neurons, regression model yun, di niyo lang napapansin noh? Yung mga BS Math alam nila yun na ganun. Ang neural network ay napakalaking regression model na hindi kayang i-calculate dati ano? Kaya nga kailangan naten ng mga ano eh, mga GPU na eh, kase napaka laking matrix nun, noh?],
  [Macapallag:], [Eto yung pag computations.],
  [Javier:], [Tas eto po yung sa dataset po dun sa...],
  [Sir Victor:], [Ito, hindi na naten issue yan ano?],
  [Javier & Valdeabella:], [Opo.],
  [Sir Victor:], [Ang hinahanap naten ay gaano ka-accurate? Pano niyo cinacalculate?],
  [Valdeabella:], [Ayan po sir, meron pong test set, test set. Ayun, sa test set po...],
  [Sir Victor:], [Hindi, sige, anong eksaktong ano niyo para macalc---anong eksaktong tawag niyo dun sa technique para macalculate kung gaano kagaling yung isang algorithm?],
  [Valdeabella:], [May iba't iba pong metrics. Accuracy, precision, recall, F1-score...],
  [Sir Victor:], [Hindi, ah sige accuracy ano? Anong ginamit niyo?],
  [Valdeabella:], [Ah true positive plus true negative over lahat po ng ano...],
  [Javier:], [Nasa documentation naman po yun.],
  [Sir Victor:], [Okay balik tayo, ilan ang algorithms niyo? Limang iba't iba?],
  [Researchers:], [Opo.],
  [Sir Victor:], [Tas pagkukumparahin niyo yun ano?],
  [Valdeabella:], [Opo.],
  [Sir Victor:], [Kung sino pinaka accurate?],
  [Valdeabella:], [Opo. Bale dito po'y ang pinaka accurate po ay SwinV2T.],
  [Sir Victor:], [Anong lumabas?],
  [Valdeabella:], [Ang accuracy po niya ay 88%.],
  [Sir Victor:], [Sino yun? Ano yun?],
  [Valdeabella:], [SwinV2 po, SwinV2T. 88% po yung accuracy niya, tas precision ay 88, recall ay 88, F1 ay 88.],
  [Sir Victor:], [Gaano kalaki ang ano niyo, dataset?],
  [Macapallag & Valdeabella:], [7,000 po.],
  [Sir Victor:], [Iniisip ko lang ha, wala bang inferential statistics para mapagcompare. Yun ang iniisip ko ih, i-send niyo nga saken yung limang algorithm. Edi wala na kong issue sa inyo noh? Ay kayo naman anong ano?],
  [Valdeabella:], [Ito po yung sa mismong statistics po namin. Ito po yung itatanong po sana namin mismo. Yan po yung nakalap naming dataset base sa literature _[showing bayesian inference dataset]_. _[inaudible]_ nail feature tas yung associated disease, tas yung preva---eto po yung mga prevalence niya para magamit sa bayesian inference.],
  [Sir Victor:], [Oh sige anong pinaka ano niyo?],
  [Valdeabella:], [So mula po jan sir, halimbawa ay beau's line, cocomputin nalang po yung prevalence niya, prevalence ng COVID-19, yung posterior probability po.],
  [Sir Victor:], [Kanino---san niyo nakuha to?],
  [Valdeabella:], [Sa mga literature po na nakalap po namin.],
  [Sir Victor:], [Ah walang open-source na dataset na naka post sa government agencies ng US for example?],
  [Valdeabella:], [Wala po sir, mahirap pong makahanap ng ganto---],
  [Sir Victor:], [Oh edi i-defend niyo nalang.],
  [Valdeabella:], [Opo.],
  [Sir Victor:], [Wala kayong choice ano?],
  [Macapallag:], [Yes po.],
  [Sir Victor:], [Wala ba silang kaparehang...sabagay kahit nga Pilipinas _[inaudible]_. Pero tayo nagsisimula nang ano eh, kaso sa health talagang wala, talagang issue yan. Kahit pa sinabi ng PSA na meron ano? Meron silang data dun sa kanilang data center, ang gagamitin mo raw ay R. Lahat ng data nandun. Magre-request ka, magpapa-book ka ano? So dun sa data center nila wala kang dala ano? Katawan mo lang tapos dapat marunong ka ng R tapos ayun magpo-process ka ng data dun, kailangan ia-anonymize mo, tas ichecheck pa nila ba---maire-request mo. Siguro makakakuha ka ng ganyan...kaya lang napakabusisi nun. Eh kayo, baha---wala naman akong tanong, ano?],
  [Valdeabella:], [Tama po kaya yung proseso po namin? Bali dun po---],
  [Sir Victor:], [Eh wala ka namang choice na ano ih, yan lang ang pagbabasehan mo ano? Parang database lang to ih.],
  [Valdeabella:], [Opo sir.],
  [Javier:], [Talaga pong pure computation lang po yan, wala pong model.],
  [Sir Victor:], [Oo, magkakaiba kase ng---oh ayun eh oh, wala data lang yan eh.],
  [Javier:], [Pwede po kayang i-average yan sir?],
  [Sir Victor:], [Anong ibig mong sabihin?],
  [Javier:], [Halimbawa po yung mga beau's line, diba po't iba't iba po yung probability na lumabas sa literature, pwede po kayang kunin nalang namin yung average para po yun po yung i-output nung---],
  [Sir Victor:], [Hindi, dapat nga ang complicated na ano niyan...],
  [Valdeabella:], [Kase pag ia-average dapat lahat ng data may---],
  [Sir Victor:], [Eh kaso kung yan lang ang data mo, wala kang choice, magiging ganun nga kasimpleng---di mo pedeng i-average, papano mo ia-average niyan?],
  [Javier:], [Ano ba yung sa calculation mo?],
  [Valdeabella:], [Kailangan ipag plus plus lahat ng population nun ano, eh ibang literature po yung---],
  [Sir Victor:], [Hindi, tsaka magkakaiba yan ng ano ah, sakit ah.],
  [Valdeabella:], [Kaya nga po.],
  [Javier:], [Hindi, yun lang pong magkakatulad na sakit.],
  [Sir Victor:], [Asan asan? Sige nga magbigay ka nga ng example.],
  [Javier:], [Meron ba dyang nakalagay na magkatulad ng sakit?],
  [Valdeabella:], [Yung sa clubbing meron jan diba? Yung sa iron deficiency nadoble.],
  [Sir Victor:], [Oh sige, asan asan?],
  [Macapallag:], [Alin ba?],
  [Valdeabella:], [Ano yun tinanggal mo na? Yung dobleng iron deficiency?],
  [Macapallag:], [Oo.],
  [Sir Victor:], [Wala ya---ano yan, magkakaiba to diba? Marami ka dito tas ito mga possibility, oh. Yan dalawa lang?],
  [Valdeabella:], [Kung sa medical diagnostics po sir, valid po kaya yung ganyang approach? Bayesian? Hindi siya talagang nagda-diagnose, kumbaga estimate lang kung ano.],
  [Sir Victor:], [Eh kase diba ang napapanahon ngayon, multiple symptoms ang chinecheck tas based on ano nga...ayun multiple symptoms na yun, yung algorithm mo ano? Usually neural networks. Oh sinasabi kung ano yung probability na eto, etong sakit na to pinaka mataas na probability na meron ka. Multiple symptoms yun. Combination ng nararamdaman ng pasyente, yung blood chemistry result...],
  [Valdeabella:], [Maano nga lang po sa data yun ano?],
  [Javier:], [Sabi rin po nung expert na nainterview namin, yung nail po is parte lang po ng diagnosis.],
  [Sir Victor:], [Kaya nga eh, eh ayan pinayagan yan eh edi ayan na, okay na saken. Wala rin namang---sinong magchecheck ng ano niyan? Ang pinaka stat ko lang naman---kaya nga hinahanap ko sa inyo accuracy eh diba?],
  [Javier:], [Opo.],
  [Sir Victor:], [Accuracy, edi ibig sabihin ano lang yun, parang percent lang yun, average lang yun. Ganun eh, so yun lang ang hahanapin ng statistician. Eh yang algorithm niyo ay edi stuck-up kayo jan sa simple ano? Isa lang ang symptoms, isa lang ang pinaghahanapan ng symptoms. Eh kung tutuusin ano yan, dapat---blood chem nga yung pinaka magandang ano.],
  [Valdeabella:], [Kaya nga po eh.],
  [Sir Victor:], [Oo, diba...],
  [Valdeabella:], [May iba't iba pang _[inaudible]_ ng medicine.],
  [Sir Victor:], [Oo, pero siguro yan yung pinaka simple. Kaya lang, gaano ka-usable yang system niyo? Gaano ka-novel? Gaano ka-useful diba?],
  [Javier:], [Parang sa tingin ko po, ang pinagkaiba yun po blood chem is---ah yun pong nail, parang mas accessible po siya sa marami kase di na po siya lumapit sa doktor agad agad.],
  [Valdeabella:], [Non-invasive. Bale for proof-of-concept lang naman po, pede pa siyang ma-improve sa future hangga't merong data.],
  [Javier:], [Tsaka sa novelty po, kadalasan pong nababasa naming studies ay hindi po siya nagdederetso po sa systemic disease, kadalasan po ay cina-classify niya lang yung mga [nail features]. Kaya po limited din po yung mga dataset na nakukuha namin.],
  [Sir Victor:], [Okay wala kayong issue saken go. Edi dun kayo mag defense sa subject specialist. Sila naman _[inaudible]_ diba? Ano?],
  [Researchers:], [Thank you po sir.],
)
