/* Consultation - 09/06/25 */

#grid(
  columns: (1fr, 3fr),
  row-gutter: 1.5em,
  [Valdeabella:],
  [...halimbawa, nadetect niya na meron kang clubbing sir, papasok siya dun sa pangalawang stage nung pipeline namin which is yung inference po ng systemic disease na manggagaling po dun sa dataset namin galing sa literature.],

  [Sir Mark:], [Na?],
  [Valdeabella:],
  [Halimbawa sir, sabi dito sa literature na to, 32% ng mga may clubbing merong cirrhosis ganyan sir. Bale dun po siya magdederive, sa literature po na maga-gather namin.],

  [Sir Mark:], [32%?],
  [Valdeabella & Javier:], [Example lang po yung sir.],
  [Sir Mark:],
  [For example sa isang nail---sabi mo nga may percentage---may mga almost the same ba na diseases sa nail? Yung mami-misinterpret mo na ibang disease pa na---parang may mga magkakatulad. For example yan [_points at the nail image_].],

  [Valdeabella:], [Ahh eto po sir, ang ano---yung pedeng malito ang doktor?],
  [Sir Mark:], [Hindi, yung model din.],
  [Valdeabella:], [Muehrcke's lines tsaka po terry's nails kase pareho silang...],
  [Sir Mark:], [Kase dapat may ganun nga, kunwari---may percentage.],
  [Valdeabella:], [Yung confidence po sir?],
  [Sir Mark:], [Oo, nakalagay nga dun yung percentage ng mga diseases.],
  [Valdeabella:], [Opo, naito po sir. Pakita po namin yung example.],
  [Sir Mark:], [Asan na?],
  [Valdeabella:],
  [Sir, di ba nabanggit niyo po nung RC, ang gusto niyo pong mangyari ay mag-eextract pa po kami ng features. Ano po yun, kami po mismo yung mag-eextract ng feature?],

  [Sir Mark:], [Oo.],
  [Valdeabella:], [Sa ano po kasi namin sir, deep learning po kami...],
  [Sir Mark:], [Eh dun sa inyo, ano bang ginamit niyo?],
  [Valdeabella:],
  [CNN model sir. Bale yung mga CNN, sila na po bahala mag extract ng mga feature. Ang problema lang po namin ay paano namin siya mai-interpret or explain. Isa po yun sa goal namin, yung ma-explain kung paano nangyari yung ganun, ganyan. [_points to the Grad-CAM visualization_] Eto pong heatmap sir, nakabase po siya sa feature extraction layer ng CNN. Kung bakit siya nag come up sa...],

  [Sir Mark:], [Ano ba kayo sa october?],
  [Researchers:], [RC pa rin po.],
  [Valdeabella:],
  [Dito sa [_points at SwinV2B Grad-CAM visualization_]---wala siyang heatmap kase ito pong model na to ay vision transformer sir. Mas malakas siya pero mas mahirap maging interpretable.Parang ganun naman po yung mga models ngayon na eh. Habang lumalakas, mas may challenges ng interpretability, explainability---malakas nga yung model, hindi mo naman alam kung pano siya nag come up sa ganoong prediction. Sa CNN madali lang po siya iinterpret gawa't meron po siyang feature extraction layer...],

  [Sir Mark:], [Mabilis na nga yan, puro naka pre-trained na naman kayo ih.],
  [Valdeabella:],
  [Sir, yung sa pre-trained po, ang ginamit po namin ay yung weights ng ImageNet. So bale yun, hindi po siya naka trained sa nails lang, naka trained po siya sa 1000 classes. pedeng car ganun, ganun, ganun. Pwede naman po namin siyang tanggalin---halos magiging ganto lang din po yung resulta kaso lang po, mas tatagal po yung training kase reset siya from scratch. Bale lahat ng parameters niya, randomized.],

  [Sir Mark:], [Ganun nga yung mga ano ih---ngayong batch nga lang ang puro pre-trained ih.],
  [Valdeabella:], [Edi sir tatanggalin na po namin yung pre-trained.],
  [Sir Mark:], [Hindi na ba pinapagamit ni ma'am Mia?],
  [Valdeabella:], [Bale ganto lang po yun sir eh...],
  [Sir Mark:], [Ngayong year lang ang puro pre-trained ang ginamit eh.],
  [Valdeabella:],
  [Parang mas pabor pa po kase siya kase mas---tulad nga po sa limitations---sa google colab, may limit lang na 4 hours. Pag tapos nun, gagamit ka ng bagong account. Pag may weights...eto halimbawa yung weights [_Indicates the code that loads the pre-trained model_], ni-load namin yung weights ng SwinV2B. From there, ita-transfer learning po namin. Sa case po na to, finine-tune po namin yung buong model.],

  [Sir Mark:], [Ano naging result?],
  [Valdeabella:],
  [Eto po sir [_Indicates the printed evaluation metrics_]. Bale eto yung pinaka malakas namin na model na vision transformer kaso mahirap din po iinterpret. So yun sir, 90% accuracy, 90% precision, 90% recall, tas 89% F1-score. Nasa taas po yung confusion matrix. Pwede naman po sir, wag na naming gawing pre-trained. Kaso ang mangyayari lang po kase diyan, tatagal lang po yung training pero halos ganyan lang din po yung results. Na-try ko na po yun ih.],

  [Sir Mark:], [Yan na yung ginamit niyo? ],
  [Valdeabella:], [Opo sir tas...],
  [Sir Mark:], [Yang model na yan na ang ginamit niyo?],
  [Valdeabella:],
  [Hindi po sir, ito pong EfficientNetV2 kase wala po itong pang explain eh [_referring to Swinv2B model_]. Itong EfficientNet, CNN siya kaya may interpretability.],

  [Sir Mark:], [Yan ang gagamitin niyo na na model jaan?],
  [Valdeabella:],
  [Opo sir, itong EfficientNet pwede naman. Eto po, ito yung na come up niya. Parang may kaniya-kaniya po kaseng strengths yung model sa ibang features.],

  [Sir Mark:], [Ganun talaga.],
  [Valdeabella:], [Halimbawa po ang EfficientNet ay malakas dito, pag dating sa ibang label...],
  [Sir Mark:], [Ano nga yung gagamitin?],
  [Valdeabella:],
  [Pwede po kaya sa app namin, pipili sila ng model? Parang merong stats dun ng model kung gaano ka-accurate ganun tas pipili sila ganun.],

  [Sir Mark:], [Pwede naman.],
  [Valdeabella:], [Parang sa GPT sir, parang pipili ka lang din ng model.],
  [Sir Mark:], [Pwede.],
  [Valdeabella:], [Para may iba iba silang choices sir.],
  [Sir Mark:], [Oo.],
  [Valdeabella:],
  [Tulad dito sa RegNet. Kita niyo sir, mas precise dito yung heatmap eh gawa't sa acral lentiginous melanoma, eto yung dinedetect sir [_points at the focus area showing model attention_]. Kita niyo mas precise siya dito. So testing tayo ngayon. Testing tayo nitong image sir. Halimbawa, ito'y kinuha ko lang po sa internet [_chooses a sample image for inference_]. Eto po yung nade-detect niyang feature. Yan po yung prediction niya. Eto po pala yung confidence sir. Kung gaano ka-confident yung model na [_inaudible_]. Yan sir, eto healthy nails sabi niya, eto acral, eto acral, eto terry's nails, eto acral [points to the models' output prediction].],

  [Sir Mark:], [Ano ba yung sakit diyan?],
  [Valdeabella:], [Ano sir, ano nga to eh, terry's nails nga po---],
  [Sir Mark:], [Ano nga diyan? Hindi ko nga alam yung sakit sa kuko eh. Alin nga diyan yun?],
  [Valdeabella:], [Paano pong sakit?],
  [Sir Mark:], [Alin yung dinedetect diyan? Kung may kulay?],
  [Valdeabella:],
  [Opo sir. Kung ano po yung na-learn ng model kung anong itsura ng terry's nails. Isa pa pong example, last [_chooses another sample image for inference_]. Ayan sir [points to the models' output prediction], eto clubbing, terry's nails, kase parang mukha siyang clubbed din eh tas terry's nails gawa nitong brownish color tas wala siyang lunula tapos white pa yung kuko niya kaya siguro ganun na-come up ng model. Clubbing yung hula niya kase mukha siyang clubbed din eh. Ganun din po dito sir. Eto koilonychia, parang mahina po yung pagkaka-interpret niya. Eto yung na-detect niya ih. Parang mali yung model na to sa paghula. Confident siya kaso confident siyang mali.],

  [Sir Mark:], [Di na kase nag pre-process ng image eh.],
  [Valdeabella:],
  [Ahh ano po to sir, test set po. Ito po yung sa---yung training lang po talaga ang pinipre-process namin gawa't sa test set po dapat di magagalaw yan. Yan po sir [_shows the training set images_]. Mga augmentations. Flipped, 50% random flip, 50% vertical flip. Nakalagay naman po yun sa paper namin. Pwede na po kaya yun sir?],

  [Sir Mark:],
  [Eh kung nade-detect niya na naman ng high accuracy eh. Na tama yung mga condition ih, edi okay na siya. Pwede na nga yan kahit nasa 60+ lang eh.],

  [Valdeabella:], [80% yung initial target namin. Lumampas na po kami dun.],
  [Sir Mark:], [Edi kunin niyo nalang yung pinaka okay.],
  [Valdeabella:],
  [Ang balak nalang po namin ngayon sir, gagawin siyang robust. So ang next step po namin ay maggagawa kami ng object detection ng nail. Kase halimbawa, paano kung may nagpasok diyan ng hindi nails? Dapat walang result nun.],

  [Macapallag:], [Mga edge cases nga po sir. Iha-handle namin yun.],
  [Valdeabella:], [Halimbawa po, nagpasok siya ng libro eh hindi naman yun nails, dapat wala siyang made-detect.],
  [Sir Mark:], [Bakit ipapasok yung libro?],
  [Valdeabella:], [Ayun nga sir, pag ano...],
  [Sir Mark:], [Eh nail ano nga eh. Ang tanga naman nun.],
  [Valdeabella:],
  [Parang pang robust lang ba sir, robustness. Para madetect na rin yung nail region para kung halimbawang malayo yung picture, macocrop niya yung nail region. Ayun po yung isa sa winowork on namin sir. Yung sa 5 pillars ng AI ethics. Dapat robust, dapat explainable. Mae-explain mo kung bakit nag come up yung AI ng ganung results. Fairness ganun.],

  [Sir Mark:],
  [Dun sa mga underlying conditions, ano yun automatic ba---kunwari clubbing---yun na talaga yung mga condition?],

  [Valdeabella:], [Base po sa literature sir.],
  [Sir Mark:], [Yun lang din o may percentage pa?],
  [Valdeabella:],
  [May percentage po sir base po sa literature kase pag---halimbawa---hindi po naten masasabi na porket clubbing ay masakit agad eh. Ganun din po sa mga doctors eh.],

  [Sir Mark:], [Yun nga, yun nga yung hinahanap ni ma'am Mia diyan eh.],
  [Valdeabella:], [Tsaka yung reliability ng nails...],
  [Javier:], [Tsaka isang ano lang po siya eh...],
  [Valdeabella:], [Isang indicators sir. Isa yun sa...],
  [Sir Mark:], [Kase yung sa image detection, mabilis na talaga siyang gawin ngayon eh. Sisiw na siya ih.],
  [Valdeabella:], [Kaya ang approach namin sir, Bayes' Theorem.],
  [Javier:], [Kung may ganto kang feature, anong probability na may ganto kang sakit.],
  [Valdeabella:], [Oo kase hindi lahat ng may clubbing, may gantong sakit. Hindi lahat ng...],
  [Sir Mark:], [Yun nga, by percentage kasi siya. Hindi siya pwedeng naka definite.],
  [Valdeabella:], [Opo sir, bale po sa literature yung reading namin jan. Okay po kaya yung ganung approach sir?],
  [Sir Mark:],
  [Okay lang naman. Eh kung naka percentage naman wala na magiging problema dun eh. Hindi mo naman sinasabing siya yung definite na result eh. Puro possibilities lang naman eh. Kaya walang mali. Possibilities nga lang eh.],

  [Javier:], [Ano pa po kayang mare-recommend sa system sir?],
  [Sir Mark:],
  [Kung nade-detect niyo na naman ng exact yung mga diseases eh. Yung ano lang, yung mga underlying. Kase yun ang hinahanap ni ma'am Mia eh.],

  [Javier:], [Ano ba tayo? General nalang?],
  [Sir Mark:], [Hindi nga daw general eh. ],
  [Valdeabella:], [Specific dapat.],
  [Sir Mark:],
  [Yung sa title ih. Specific ih. Kaya nga sabi ko nga, kung may nagkakaparehas ba kung 30% na ganto. May specific na underlying conditions ba?],

  [Valdeabella:],
  [Ahh halimbawa sir ano---halimbawa lang po ha---sir sa clubbing tsaka sa terry's nails, pareho silang pwedeng mag cause ng heart failure.],

  [Sir Mark:], [Oo, o may naka connect pa ba sa kaniya na underlying?],
  [Valdeabella:], [Oo nga noh.],
  [Sir Mark:],
  [Yun kase yung challenges dun ih. Medyo nakakalito ih, yung ganun. Pati model malilito ih. Yun yung sinosolve talaga ng machine learning ih. Yung may mga ganung mga same. Paano mo ii-specify ng ayos? Paano mo madedetect na yun talaga siya? Although kung ganun ngang naka percentage, okay lang naman.],

  [Valdeabella:],
  [Yung dun po pala sa ano sir, iniisip namin kung paano namin ii-scale yung confidence ng model sa inference. Halimbawa...],

  [Sir Mark:], [Saang model ba yan? Diyan sa detection o dun sa pag detect na ng underlying?],
  [Valdeabella:],
  [Dito po sa model na to, paano namin siya ii-scale dun sa inference. Halimbawa, sa clubbing sinasabi niya ay 30% may cirrhosis. Paano kung halimbawa nasa 60% lang yung confidence ng model na clubbing to? Paano namin siya ii-scale dun sa result?],

  [Sir Mark:], [May formula din dun eh. Pede ngang i-base mo din sa confusion matrix yan ih.],
  [Valdeabella:], [Ahh yung ano, kung paano...],
  [Sir Mark:], [Sa confusion para simple nalang. Kase kung ilan yung nadedetect niyang ano...],
  [Valdeabella:], [Kung gaano siya katama sa feature na yun?],
  [Sir Mark:], [Oo.],
  [Valdeabella:], [Ahh oo nga noh.],
  [Sir Mark:], [Yun yung pinaka simple. Pero kung gusto mong advanced, edi i-neural mo din.],
  [Valdeabella:], [Panibagong challenge din yun sir. Paano namin gagawing explainable din yun.],
  [Sir Mark:], [Ganun nalang, sa confusion matrix nalang. Simple lang.],
  [Valdeabella:], [Sige po. Di ko naisip yun ah. May maire-recommend pa po kayo sir?],
  [Sir Mark:],
  [Parang wala naman. Kase kung nadedetect niyo na ih. Hayaan niyo na yan, dun na kayo sa next step kase baka masira pa ih. Kung nadedetect niyo na ng okay.],

  [Javier:], [Sa pre-trained po sir, okay lang yun?],
  [Sir Mark:], [Pwede na naman din. Pero nag try kayo sa hindi naka pre-trained? Yung zero?],
  [Valdeabella:], [Opo sir, mas matagal lang po yung ano...],
  [Sir Mark:], [Edi ilagay niyo nalang dun. i-indicate niyo nalang sa document. Basta nakalagay.],
  [Javier:], [Na naggamit po kami ng...],
  [Sir Mark:],
  [Oo yung ganun. Isama niyo nalang dun sa mga ginamit niyo. Di ba yung mga model na yan, tas sama niyo nalang yun. Eto---di ba naka docu naman yun?],

  [Valdeabella:], [Opo.],
  [Sir Mark:], [Eto ginamit niyo, yung sa inyong sarili, ito yung mga naging results. ],
  [Valdeabella:], [Ahh bale ilalagay din po namin lahat ng naging experiments namin?],
  [Sir Mark:],
  [Naandun sa docu lahat. Kase kung hindi nga yun ang gagamitin niyo ih. Para may basis kung bakit yan na yung path niyo.],

  [Valdeabella:], [Iniisip ko po kasi baka masyadong maging...],
  [Sir Mark:],
  [Experimental kasi yan ih. Nakalagay talaga yun. Inexperiment mo naman lahat talaga ih. Ipag-iinclude niyo nalang lahat.],

  [Valdeabella:], [Sige po sir.],
  [Sir Mark:], [Edi dun na kayo sa next step. Sa underlying. So yun na. Naka-web yan ano? Interface yan?],
  [Valdeabella:], [Opo.],
  [Sir Mark:], [Ano yan naka mobile? Hindi?],
  [Valdeabella:], [Sa web po sir.],
  [Javier:], [Pwede po kahit saan.],
  [Sir Mark:], [Pwede daw kahit saan eh.],
  [Valdeabella:], [Web sa cellphone sir.],
  [Sir Mark:], [Pero kung sa ganyan, naka mobile talaga dapat. Kaya naman ng WebU yan eh. Kaso naka ano...],
  [Javier:], [May internet sir.],
  [Sir Mark:],
  [Oo. Yung capture naman sa mobile, image din naman yun ih. Pinipicturan niya lang, ganun din naman. Sabagay sa FOD pa naman. Yun yung kailangan. Ikaw maggagawa niyan ih. Edi mas maganda. Sige next step na kayo. Okay na naman pala ih. Antaas na ih.],

  [Javier:], [Salamat po sir.],
  [Sir Mark:], [Yung iba kase nakaka-affect din yung background sa quality. Pag ini-AI mo naman _[inaudible]_.],
  [Javier:], [Pwede po kayang sabihin naman dun sa web na dapat yung background is clear ganun.],
  [Sir Mark:], [Pwede.],
  [Valdeabella:], [Ganun naman din sa ibang applications eh. Dapat ano, for the best results, dapat...],
  [Sir Mark:],
  [Pero kung pang mga AI talaga, ikaw na mag-aadjust dun. Parang sa CamScanner di ba? Ikaw na yung nag-aano. Ikaw na. Eh tsaka na yun, yun na muna ang gamitin niyo. Mga extra na yun.],

  [Researchers:], [Salamat po sir.],
)
